import { expect } from 'e2e'
import { expectRoute, nativePlatforms, test } from './fixtures'

const root = '//*[@id="application-blocks-demo"]'

test.describe('native B4 Application Blocks', { platforms: nativePlatforms, requires: ['miniProgram'] }, () => {
  test.beforeEach(async ({ miniProgram }) => {
    await miniProgram.reLaunch('/blocks-lab/application/index')
    await expectRoute(miniProgram, '/blocks-lab/application/index')
    await expect(miniProgram.locator(root)).toContainText('Labelled in-memory data only.')
  })
  test.afterEach(async ({ miniProgram }) => { expect(await miniProgram.errors()).toEqual([]) })

  test('settings accept controlled changes and preserve rejected values', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    const notifications = screen.getByRole('switch', { name: 'Local notifications', exact: true })
    await expect(notifications).toHaveAttribute('aria-checked', 'false')
    await notifications.tap()
    await expect(notifications).toHaveAttribute('aria-checked', 'true')
    await expect(screen.getByRole('switch', { name: 'Managed setting', exact: true })).toBeDisabled()
    await expect(screen.getByRole('switch', { name: 'Pending setting', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Density: Unavailable', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Density: Dense', exact: true }).tap()
    await expect(demo).toContainText('Local preference rejected; value preserved')
    await expect(screen.getByRole('button', { name: 'Density: Comfortable', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await screen.getByRole('button', { name: 'Density: Compact', exact: true }).tap()
    await expect(demo).toContainText('Local preference updated: density=compact')
    await expect(screen.getByRole('button', { name: 'Density: Compact', exact: true })).toBeDisabled()
  })

  test('onboarding bounds navigation and keeps close available while pending', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Onboarding', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Back', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Next onboarding step', exact: true }).tap()
    await expect(demo).toContainText('Step 2 of 2')
    await expect(screen.getByRole('button', { name: 'Finish onboarding', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Back', exact: true }).tap()
    await expect(demo).toContainText('Step 1 of 2')
    await screen.getByRole('switch', { name: 'Show pending state', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Next onboarding step', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Close onboarding', exact: true }).tap()
    await expect(demo).toContainText('Local guide closed without completion')
    await screen.getByRole('switch', { name: 'Show pending state', exact: true }).tap()
    await screen.getByRole('button', { name: 'Reopen local guide', exact: true }).tap()
    await screen.getByRole('button', { name: 'Next onboarding step', exact: true }).tap()
    await screen.getByRole('switch', { name: 'I reviewed the local guide', exact: true }).tap()
    await screen.getByRole('button', { name: 'Finish onboarding', exact: true }).tap()
    await expect(demo).toContainText('Local guide completed')
  })

  test('multi-step form validates preserves values and adds a real local summary row', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Form', exact: true }).tap()
    await screen.getByRole('button', { name: 'Next form step', exact: true }).tap()
    await expect(demo).toContainText('Enter an applicant name.')
    await expect(demo).toContainText('Choose a team.')
    await screen.getByPlaceholder('Enter a local applicant name').fill('Admin')
    await screen.getByRole('button', { name: 'Team: Design', exact: true }).tap()
    await screen.getByRole('button', { name: 'Next form step', exact: true }).tap()
    await expect(demo).toContainText('This name is reserved or already exists in the local application list.')
    await screen.getByPlaceholder('Enter a local applicant name').fill('Ada')
    await screen.getByRole('button', { name: 'Next form step', exact: true }).tap()
    await expect(demo).toContainText('Step 2 of 2: Review and consent')
    await screen.getByRole('button', { name: 'Submit application', exact: true }).tap()
    await expect(demo).toContainText('Consent is required for local processing.')
    await screen.getByRole('button', { name: 'Previous form step', exact: true }).tap()
    await expect(screen.getByPlaceholder('Enter a local applicant name')).toHaveValue('Ada')
    await expect(screen.getByRole('button', { name: 'Team: Design', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await screen.getByRole('button', { name: 'Next form step', exact: true }).tap()
    await screen.getByRole('switch', { name: 'Consent to local processing', exact: true }).tap()
    await screen.getByRole('button', { name: 'Submit application', exact: true }).tap()
    await expect(demo).toContainText('Local application saved: Ada')
    await screen.getByRole('button', { name: 'Submit application', exact: true }).tap()
    await expect(demo).toContainText('This name is reserved or already exists in the local application list.')
    await screen.getByRole('button', { name: 'Demo: Summary', exact: true }).tap()
    await expect(demo).toContainText('Ada')
    await expect(miniProgram.locator('//*[@data-summary-value="applications"]')).toHaveText('2')
    await screen.getByRole('button', { name: 'Period: This session', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-summary-value="applications"]')).toHaveText('1')
  })

  test('timeline retry validates input and records the actual local import', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Timeline', exact: true }).tap()
    await screen.getByRole('button', { name: 'Retry Local import', exact: true }).tap()
    await expect(demo).toContainText('Enter a unique import name before retrying.')
    await screen.getByPlaceholder('Enter a unique import name').fill('Quinn')
    await screen.getByRole('button', { name: 'Retry Local import', exact: true }).tap()
    await expect(demo).toContainText('Added Quinn to the local application list.')
    await expect(screen.getByRole('button', { name: 'Retry Local import', exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: 'Details for Local import', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-application-result="timeline"]')).toContainText('Added Quinn')
    await screen.getByRole('button', { name: 'Demo: Summary', exact: true }).tap()
    await expect(demo).toContainText('Quinn')
    await expect(miniProgram.locator('//*[@data-summary-value="applications"]')).toHaveText('2')
  })

  test('summary period error retry and empty states retain honest context', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Summary', exact: true }).tap()
    await expect(demo).toContainText('River')
    await screen.getByRole('button', { name: 'Show local summary error', exact: true }).tap()
    await expect(demo).toContainText('Local summary error example')
    await expect(demo).toContainText('River')
    await screen.getByRole('button', { name: 'Retry summary', exact: true }).tap()
    await expect(demo).toContainText('Local summary acknowledgements: 1')
    await expect(screen.getByRole('button', { name: 'Retry summary', exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: 'Period: This session', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-summary-value="applications"]')).toHaveText('0')
    await screen.getByRole('switch', { name: 'Show empty data', exact: true }).tap()
    await expect(demo).toContainText('No summary data')
  })

  test('booking rechecks local availability rejects conflicts and cancels accepted records', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Booking', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '09:00', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '11:00', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Request booking', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '10:00', exact: true }).tap()
    await screen.getByRole('button', { name: 'Reserve 10:00 in local ledger', exact: true }).tap()
    await screen.getByRole('button', { name: 'Request booking', exact: true }).tap()
    await expect(demo).toContainText('Local booking rejected; nothing booked for you')
    await expect(demo).toContainText('Local ledger rows: 1')
    await expect(screen.getByRole('button', { name: 'Request booking', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Sample day two', exact: true }).tap()
    await screen.getByRole('button', { name: '14:00', exact: true }).tap()
    await screen.getByRole('button', { name: 'Request booking', exact: true }).tap()
    await expect(demo).toContainText('Local booking confirmed: 14:00')
    await expect(demo).toContainText('Local ledger rows: 2')
    await screen.getByRole('switch', { name: 'Show pending state', exact: true }).tap()
    await screen.getByRole('button', { name: 'Cancel booking', exact: true }).tap()
    await expect(demo).toContainText('Local booking cancelled; no external service called')
    await expect(demo).toContainText('Local ledger rows: 1')
  })

  test('people paging filters grants and confirmed mutations update local records', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: People', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Details for Casey', exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: 'Load more people', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Details for Casey', exact: true })).toBeEnabled()
    await screen.getByRole('button', { name: 'Details for Rowan', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Remove Rowan', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Approve Rowan', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Close person details', exact: true }).tap()
    await screen.getByRole('button', { name: 'People: Pending', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Details for Rowan', exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: 'Details for Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Role: Reviewer', exact: true }).tap()
    await expect(demo).toContainText('Local person updated: Maya (role)')
    await screen.getByRole('button', { name: 'Approve Maya', exact: true }).tap()
    await expect(demo).toContainText('No people in this view')
    await screen.getByRole('button', { name: 'People: Active', exact: true }).tap()
    await screen.getByRole('button', { name: 'Details for Maya', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Approve Maya', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Status: Inactive', exact: true }).tap()
    await expect(demo).toContainText('Local person updated: Maya (status)')
    await screen.getByRole('button', { name: 'People: All', exact: true }).tap()
    await screen.getByRole('button', { name: 'Details for Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Remove Maya', exact: true }).tap()
    await expect(screen.getByRole('group', { name: 'Confirm local removal', exact: true })).toContainText('Maya')
    await screen.getByRole('button', { name: 'People: Active', exact: true }).tap()
    await screen.getByRole('button', { name: 'Details for Rowan', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Confirm local removal', exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: 'People: All', exact: true }).tap()
    await screen.getByRole('button', { name: 'Details for Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Remove Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Close person details', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Confirm local removal', exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: 'Details for Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Remove Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Keep local person', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Remove Maya', exact: true })).toBeEnabled()
    await screen.getByRole('button', { name: 'Remove Maya', exact: true }).tap()
    await screen.getByRole('button', { name: 'Confirm local removal', exact: true }).tap()
    await expect(demo).toContainText('Removed Maya from the local list')
    await expect(screen.getByRole('button', { name: 'Details for Maya', exact: true })).toHaveCount(0)
  })

  test('injected disabled pending and empty states preserve evidence without mutations', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('switch', { name: 'Disable mutations', exact: true }).tap()
    await expect(screen.getByRole('switch', { name: 'Local notifications', exact: true })).toBeDisabled()
    await expect(demo).toContainText('No preference changes')
    await screen.getByRole('switch', { name: 'Disable mutations', exact: true }).tap()
    await screen.getByRole('switch', { name: 'Show pending state', exact: true }).tap()
    await expect(demo).toContainText('Local preview account')
    await expect(screen.getByRole('button', { name: 'Density: Compact', exact: true })).toBeDisabled()
    await screen.getByRole('switch', { name: 'Show pending state', exact: true }).tap()
    await screen.getByRole('switch', { name: 'Show empty data', exact: true }).tap()
    for (const [panel, text] of [['Settings', 'No settings available'], ['Onboarding', 'No onboarding step available'], ['Form', 'No form step available'], ['Timeline', 'No history yet'], ['Summary', 'No summary data'], ['Booking', 'No dates available'], ['People', 'No people in this view']]) {
      await screen.getByRole('button', { name: `Demo: ${panel}`, exact: true }).tap()
      await expect(demo).toContainText(text)
    }
    if (miniProgram.mode === 'devtools') { await miniProgram.screenshot('native-application-empty-people') }
  })
})
