import { expect } from 'e2e'
import { expectRoute, nativePlatforms, test } from './fixtures'

const root = '//*[@id="data-workspace-demo"]'
test.describe('native B5 mobile data workspace', { platforms: nativePlatforms, requires: ['miniProgram'] }, () => {
  test.beforeEach(async ({ miniProgram }) => {
    await miniProgram.reLaunch('/blocks-lab/data-workspace/index')
    await expectRoute(miniProgram, '/blocks-lab/data-workspace/index')
  })
  test.afterEach(async ({ miniProgram }) => { expect(await miniProgram.errors()).toEqual([]) })

  test('chart derives values shows zero and detail accepts twelve and rejects thirteen categories', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await expect(miniProgram.locator('//*[@data-chart-id="todo"]')).toContainText('To do: 8 planned hours')
    await expect(miniProgram.locator('//*[@data-chart-id="doing"]')).toContainText('In progress: 2 planned hours')
    await expect(miniProgram.locator('//*[@data-chart-id="done"]')).toContainText('Done: 0 planned hours')
    await screen.getByRole('button', { name: 'Inspect To do', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-chart-detail]')).toContainText('Planned hours summed from local task records')
    await expect(screen.getByRole('button', { name: 'Inspect To do', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Toggle twelve categories', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-chart-id]')).toHaveCount(12)
    await expect(miniProgram.locator('//*[@data-chart-id="unassigned-11"]')).toContainText('long label that remains readable on mobile: 0 planned hours')
    if (miniProgram.mode === 'devtools') { await miniProgram.screenshot('data-chart-twelve-categories') }
    await screen.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).tap()
    await expect(demo).toContainText('Chart configuration rejected: at most 12 categories')
    await expect(miniProgram.locator('//*[@data-chart-id]')).toHaveCount(0)
    await screen.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-chart-id]')).toHaveCount(12)
  })

  test('schedule bounds day week navigation and disabled dates preserve controlled selection', async ({ miniProgram, screen }) => {
    await screen.getByRole('button', { name: 'Demo: Schedule', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Previous period', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Choose date 2026-10-10', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Choose Gamma planning slot', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Day view', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-schedule-date]')).toHaveCount(1)
    await screen.getByRole('button', { name: 'Next period', exact: true }).tap()
    await screen.getByRole('button', { name: 'Choose date 2026-10-09', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-schedule-selection]')).toContainText('2026-10-09')
    await screen.getByRole('button', { name: 'Week view', exact: true }).tap()
    await screen.getByRole('button', { name: 'Next period', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-schedule-view]')).toContainText('2026-10-16')
    await expect(screen.getByRole('button', { name: 'Next period', exact: true })).toBeDisabled()
    await expect(miniProgram.locator('//*[@data-schedule-selection]')).toContainText('2026-10-09')
    await screen.getByRole('button', { name: 'Previous period', exact: true }).tap()
    await screen.getByRole('button', { name: 'Previous period', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-schedule-view]')).toContainText('2026-10-08')
    await expect(screen.getByRole('button', { name: 'Previous period', exact: true })).toBeDisabled()
  })

  test('schedule rejects occupied slots applies date filters and retains unavailable selection', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Schedule', exact: true }).tap()
    await screen.getByRole('button', { name: 'Toggle Alpha ledger conflict', exact: true }).tap()
    await screen.getByRole('button', { name: 'Choose Alpha planning slot', exact: true }).tap()
    await expect(demo).toContainText('Local slot rejected: Alpha is occupied')
    await expect(miniProgram.locator('//*[@data-workspace-result="schedule"]')).toContainText('No local slot chosen')
    await screen.getByRole('button', { name: 'Choose Beta planning slot', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-workspace-result="schedule"]')).toContainText('Local slot chosen: Beta on 2026-10-09')
    await screen.getByRole('button', { name: 'Make selected date unavailable', exact: true }).tap()
    await expect(demo).toContainText('Selected date is no longer available')
    await expect(miniProgram.locator('//*[@data-schedule-selection]')).toContainText('2026-10-09')
    await screen.getByRole('button', { name: 'Demo: Grid', exact: true }).tap()
    await screen.getByRole('button', { name: 'Filter grid to selected date', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-record]')).toHaveCount(1)
    await expect(miniProgram.locator('//*[@data-grid-record="beta"]')).toContainText('Beta')
    await expect(miniProgram.locator('//*[@data-grid-date-filter]')).toContainText('2026-10-09')
    await screen.getByRole('button', { name: 'Clear date filter', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-page]')).toContainText('4 records')
  })

  test('board allowed rejected and approved moves change cards and derived chart totals', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Board', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Move Alpha to To do', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Move Beta to Done', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Move Gamma to In progress', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Move Alpha to In progress', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-board-column="doing"]//*[@data-board-card="alpha"]')).toHaveCount(1)
    await screen.getByRole('button', { name: 'Move Alpha to Done', exact: true }).tap()
    await expect(demo).toContainText('Move rejected: approve this task before Done')
    await expect(miniProgram.locator('//*[@data-board-column="doing"]//*[@data-board-card="alpha"]')).toHaveCount(1)
    await expect(miniProgram.locator('//*[@data-board-column="done"]//*[@data-board-card="alpha"]')).toHaveCount(0)
    await screen.getByRole('button', { name: 'Approve Alpha', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Approve Alpha', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Inspect Alpha', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-board-detail]')).toContainText('Approved')
    await screen.getByRole('button', { name: 'Move Alpha to Done', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-board-column="done"]//*[@data-board-card="alpha"]')).toHaveCount(1)
    if (miniProgram.mode === 'devtools') { await miniProgram.screenshot('data-board-approved-move') }
    await screen.getByRole('button', { name: 'Demo: Chart', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-chart-id="todo"]')).toContainText('To do: 5 planned hours')
    await expect(miniProgram.locator('//*[@data-chart-id="done"]')).toContainText('Done: 3 planned hours')
  })

  test('grid preserves base columns expansion filtering grouping and bounded pages', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Grid', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-record]')).toHaveCount(2)
    await expect(screen.getByRole('button', { name: 'Previous records', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Column: Hours', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-cell="hours"]')).toHaveCount(0)
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toContainText('Alpha')
    await screen.getByRole('button', { name: 'Column: Hours', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toContainText('Hours: 3')
    await screen.getByRole('button', { name: 'Expand Alpha', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]//*[@data-grid-detail]')).toContainText('Alpha planning on 2026-10-08')
    await screen.getByRole('button', { name: 'Collapse Alpha', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-detail]')).toHaveCount(0)
    await screen.getByRole('button', { name: 'Group records', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-group]')).toHaveCount(2)
    await expect(demo).toContainText('Owner: Avery')
    await screen.getByPlaceholder('Filter local records').fill('Bo')
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toHaveCount(0)
    await expect(miniProgram.locator('//*[@data-grid-record="beta"]')).toHaveCount(1)
    await expect(miniProgram.locator('//*[@data-grid-record="delta"]')).toHaveCount(1)
    await expect(miniProgram.locator('//*[@data-grid-group]')).toHaveCount(1)
    await screen.getByPlaceholder('Filter local records').fill('no match')
    await expect(demo).toContainText('No matching records')
    await screen.getByPlaceholder('Filter local records').fill('')
    await screen.getByRole('button', { name: 'Next records', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-page]')).toContainText('Page 2 of 2')
    await expect(screen.getByRole('button', { name: 'Edit Gamma', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Next records', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Previous records', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toHaveCount(1)
  })

  test('grid editing preserves drafts on field and application rejection then updates real records', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    await screen.getByRole('button', { name: 'Demo: Grid', exact: true }).tap()
    await screen.getByRole('button', { name: 'Edit Alpha', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Save record', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: 'Next records', exact: true })).toBeDisabled()
    await screen.getByPlaceholder('Edit Hours').fill('9')
    await screen.getByRole('button', { name: 'Save record', exact: true }).tap()
    await expect(demo).toContainText('Hours must be an integer from 0 to 8.')
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toContainText('Hours: 3')
    await screen.getByPlaceholder('Edit Hours').fill('4')
    await screen.getByPlaceholder('Edit Title').fill('Beta')
    await screen.getByRole('button', { name: 'Save record', exact: true }).tap()
    await expect(demo).toContainText('Save rejected: another local record already uses this title.')
    await expect(screen.getByPlaceholder('Edit Title')).toHaveValue('Beta')
    await screen.getByPlaceholder('Edit Title').fill('Alpha revised')
    await screen.getByRole('button', { name: 'Save record', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toContainText('Alpha revised')
    await expect(miniProgram.locator('//*[@data-grid-record="alpha"]')).toContainText('Hours: 4')
    await expect(screen.getByPlaceholder('Edit Title')).toHaveCount(0)
    if (miniProgram.mode === 'devtools') { await miniProgram.screenshot('data-grid-accepted-edit') }
    await screen.getByRole('button', { name: 'Edit Alpha revised', exact: true }).tap()
    await screen.getByRole('button', { name: 'Toggle busy', exact: true }).tap()
    await expect(screen.getByRole('button', { name: 'Save record', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: 'Cancel edit', exact: true }).tap()
    await expect(screen.getByPlaceholder('Edit Title')).toHaveCount(0)
    await screen.getByRole('button', { name: 'Toggle busy', exact: true }).tap()
    await screen.getByRole('button', { name: 'Demo: Chart', exact: true }).tap()
    await expect(miniProgram.locator('//*[@data-chart-id="todo"]')).toContainText('To do: 9 planned hours')
  })

  test('all blocks retain evidence across disabled loading busy error empty and invalid states', async ({ miniProgram, screen }) => {
    const demo = miniProgram.locator(root)
    for (const [panel, action, emptyText, invalidText] of [
      ['Chart', 'Inspect To do', 'No chart data', 'at most 12 categories'],
      ['Schedule', 'Next period', 'No events on this date', 'valid ISO dates'],
      ['Board', 'Move Alpha to In progress', 'No cards in this column', 'at most 50 cards'],
      ['Grid', 'Edit Alpha', 'No matching records', 'page size 1–50'],
    ] as const) {
      await screen.getByRole('button', { name: `Demo: ${panel}`, exact: true }).tap()
      for (const state of ['disabled', 'loading', 'busy']) {
        await screen.getByRole('button', { name: `Toggle ${state}`, exact: true }).tap()
        await expect(screen.getByRole('button', { name: action, exact: true })).toBeDisabled()
        await screen.getByRole('button', { name: `Toggle ${state}`, exact: true }).tap()
        await expect(screen.getByRole('button', { name: action, exact: true })).toBeEnabled()
      }
      await screen.getByRole('button', { name: 'Toggle application error', exact: true }).tap()
      await expect(demo).toContainText('Injected local application error; existing data is retained.')
      await expect(screen.getByRole('button', { name: action, exact: true })).toBeEnabled()
      await screen.getByRole('button', { name: 'Toggle application error', exact: true }).tap()
      await screen.getByRole('button', { name: 'Toggle empty', exact: true }).tap()
      await expect(demo).toContainText(emptyText)
      await screen.getByRole('button', { name: 'Toggle empty', exact: true }).tap()
      await screen.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).tap()
      await expect(demo).toContainText(invalidText)
      await screen.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).tap()
      await expect(screen.getByRole('button', { name: action, exact: true })).toBeEnabled()
    }
  })
})
