import type { MiniProgramFixture } from '../../engines/wechat'
import { expect } from 'e2e'
import { expectRoute, nativePlatforms, test } from './fixtures'

const route = '/blocks-lab/retail/index'
const result = (miniProgram: MiniProgramFixture, unit: string) => miniProgram.locator(`//*[@data-retail-result="${unit}"]`)

async function enter(miniProgram: MiniProgramFixture) {
  await miniProgram.reLaunch(route)
  await expectRoute(miniProgram, route)
}

test.describe('native retail tools', { platforms: nativePlatforms, requires: ['miniProgram'] }, () => {
  test.afterEach(async ({ miniProgram }) => { expect(await miniProgram.errors()).toEqual([]) })

  test('coupons: application claim acceptance, stale eligibility rejection and controlled selection', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await expect(screen.getByRole('button', { name: '领取 会员券', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '选择 已使用券', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '选择 过期券', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '领取 新人券', exact: true }).tap()
    await expect(result(miniProgram, 'coupons')).toContainText('尚未变更券状态')
    await expect(screen.getByRole('button', { name: '选择 已领运费券', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '取消本地领取', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '领取 新人券', exact: true })).toBeEnabled()
    await screen.getByRole('button', { name: '领取 新人券', exact: true }).tap()
    await screen.getByRole('button', { name: '接受本地领取', exact: true }).tap()
    await expect(result(miniProgram, 'coupons')).toContainText('本地已领取：新人券')
    await screen.getByRole('button', { name: '选择 新人券', exact: true }).tap()
    await expect(result(miniProgram, 'coupons')).toContainText('本地已选择：新人券')
    await expect(screen.getByRole('button', { name: '选择 新人券', exact: true })).toBeDisabled()

    await enter(miniProgram)
    await screen.getByRole('button', { name: '领取 新人券', exact: true }).tap()
    await screen.getByRole('button', { name: '撤销待处理优惠资格', exact: true }).tap()
    await screen.getByRole('button', { name: '接受本地领取', exact: true }).tap()
    await expect(screen.getByText('应用拒绝领取：资格已变化，券未领取。', { exact: true })).toBeVisible()
    await expect(screen.getByRole('button', { name: '领取 新人券', exact: true })).toBeDisabled()
  })

  test('receipt: explicit grants, rejected and accepted local after-sale, no payment or download success', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await screen.getByRole('button', { name: '凭证示例', exact: true }).tap()
    await expect(screen.getByText('实付 ¥173.00', { exact: true })).toBeVisible()
    await expect(screen.getByRole('button', { name: '下载凭证', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '联系商家', exact: true }).tap()
    await expect(screen.getByText('本地联系说明：请接入应用自有客服渠道。此示例没有发送消息。', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '关闭联系说明', exact: true }).tap()
    await screen.getByRole('button', { name: '申请退款', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '联系商家', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '拒绝本地售后', exact: true }).tap()
    await expect(screen.getByText('应用拒绝本地售后请求；订单未改变。', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '申请退款', exact: true }).tap()
    await screen.getByRole('button', { name: '接受本地售后', exact: true }).tap()
    await expect(result(miniProgram, 'receipt')).toContainText('没有执行退款')
    await expect(screen.getByText('售后中 · 已支付', { exact: true })).toBeVisible()
    await expect(screen.getByRole('button', { name: '申请退款', exact: true })).toBeDisabled()
    await expect(screen.getByText('实付 ¥173.00', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '授权下载意图', exact: true }).tap()
    await screen.getByRole('button', { name: '下载凭证', exact: true }).tap()
    await expect(result(miniProgram, 'receipt')).toContainText('未连接文件适配器，未下载文件')
  })

  test('reviews: application validation, retained rejected draft, accepted local list and helpful guard', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await screen.getByRole('button', { name: '评价示例', exact: true }).tap()
    await screen.getByRole('button', { name: '提交评价', exact: true }).tap()
    await expect(screen.getByText('应用校验：请选择 1–5 分，并填写至少 5 个字。', { exact: true })).toBeVisible()
    await miniProgram.commitNumber('//input[@aria-label="评价评分"]', 5)
    const body = miniProgram.locator('//textarea[@aria-label="评价内容"]')
    await body.fill('这是一条真实输入的本地评价')
    await screen.getByRole('button', { name: '提交评价', exact: true }).tap()
    await expect(result(miniProgram, 'reviews')).toContainText('尚未加入列表')
    await expect(body).toBeDisabled()
    await screen.getByRole('button', { name: '拒绝本地评价', exact: true }).tap()
    await expect(body).toHaveValue('这是一条真实输入的本地评价')
    await expect(screen.getByText('应用拒绝本次提交；草稿已保留。', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '提交评价', exact: true }).tap()
    await screen.getByRole('button', { name: '接受本地评价', exact: true }).tap()
    await expect(result(miniProgram, 'reviews')).toContainText('本地评价数：3')
    await expect(screen.getByText('这是一条真实输入的本地评价', { exact: true })).toBeVisible()
    await expect(body).toHaveValue('')
    await screen.getByRole('button', { name: '认为 本地读者 的评价有帮助', exact: true }).tap()
    await expect(result(miniProgram, 'reviews')).toContainText('本地有帮助计数：3')
    await expect(screen.getByRole('button', { name: '认为 本地读者 的评价有帮助', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '认为 受限读者 的评价有帮助', exact: true })).toBeDisabled()
  })

  test('wishlist: reused product controls, stock and permission denial, application rejection and membership removal', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await screen.getByRole('button', { name: '收藏示例', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '雾蓝餐盘组 已售罄', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '将 Varo Link 加入购物车', exact: true })).toBeDisabled()
    const deniedViews = screen.getByRole('button', { name: '查看 Varo Link', exact: true })
    await expect(deniedViews).toHaveCount(2)
    await expect(deniedViews.first()).toBeDisabled()
    await expect(deniedViews.last()).toBeDisabled()
    await expect(screen.getByRole('button', { name: '移出收藏 Varo Link', exact: true })).toBeDisabled()
    await expect(result(miniProgram, 'wishlist')).toContainText('本地购物袋数量：0')
    await screen.getByRole('button', { name: '拒绝下一次收藏操作', exact: true }).tap()
    await screen.getByRole('button', { name: '查看 云感午休毯', exact: true }).first().tap()
    await expect(screen.getByText('应用拒绝本次操作；收藏与购物袋未改变。', { exact: true })).toBeVisible()
    await expect(screen.getByRole('button', { name: '关闭本地商品内容', exact: true })).toHaveCount(0)
    await expect(result(miniProgram, 'wishlist')).toContainText('本地购物袋数量：0')
    await screen.getByRole('button', { name: '查看 云感午休毯', exact: true }).first().tap()
    await expect(result(miniProgram, 'wishlist')).toContainText('本地查看：云感午休毯')
    await screen.getByRole('button', { name: '关闭本地商品内容', exact: true }).tap()
    await screen.getByRole('button', { name: '拒绝下一次收藏操作', exact: true }).tap()
    const add = screen.getByRole('button', { name: '将 云感午休毯 加入购物车', exact: true })
    await add.tap()
    await expect(screen.getByText('应用拒绝本次操作；收藏与购物袋未改变。', { exact: true })).toBeVisible()
    await add.tap()
    await expect(result(miniProgram, 'wishlist')).toContainText('本地购物袋数量：1')
    for (let count = 2; count <= 4; count++) {
      await add.tap()
      await expect(result(miniProgram, 'wishlist')).toContainText(`本地购物袋数量：${count}`)
    }
    await add.tap()
    await expect(screen.getByText('应用拒绝加购：本地购物袋数量已达库存。', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '移出收藏 云感午休毯', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '将 云感午休毯 加入购物车', exact: true })).toHaveCount(0)
    await expect(result(miniProgram, 'wishlist')).toContainText('本地已移出收藏：云感午休毯')
  })

  test('comparison: every field remains readable, fourth product rejected visibly and removable', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await screen.getByRole('button', { name: '比较示例', exact: true }).tap()
    await expect(screen.getByText('保修说明', { exact: true })).toBeVisible()
    await expect(screen.getByText('未提供', { exact: true })).toHaveCount(3)
    await expect(screen.getByRole('button', { name: '移出比较 Varo Link', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '查看比较商品 Varo Link', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '查看比较商品 云感午休毯', exact: true }).tap()
    await expect(result(miniProgram, 'comparison')).toContainText('本地查看比较商品：云感午休毯')
    await screen.getByRole('button', { name: '关闭比较详情', exact: true }).tap()
    await screen.getByRole('button', { name: '注入第四件比较商品', exact: true }).tap()
    await expect(result(miniProgram, 'comparison')).toContainText('本地比较数量：4')
    await expect(screen.getByText(/已选择 4 件，超过 3 件上限/)).toBeVisible()
    await expect(screen.getByRole('button', { name: /移出比较 / })).toHaveCount(4)
    await expect(screen.getByText('保修说明', { exact: true })).toHaveCount(0)
    await screen.getByRole('button', { name: '移出比较 Varo Buds Mini', exact: true }).tap()
    await expect(result(miniProgram, 'comparison')).toContainText('本地比较数量：3')
    await expect(screen.getByText('保修说明', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '长内容状态', exact: true }).tap()
    await expect(screen.getByText(/订单与服务承诺请以真实商家的确认结果为准。/)).toHaveCount(3)
  })

  test('filters: draft isolation, cancel, reset, rejected category and accepted sorted stock results', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await screen.getByRole('button', { name: '筛选示例', exact: true }).tap()
    const committed = miniProgram.locator('//*[@data-retail-committed="filters"]')
    const products = miniProgram.locator('//*[@data-retail-filter-product="true"]')
    await expect(products).toHaveCount(4)
    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '应用商品筛选', exact: true })).toBeDisabled()
    await expect(screen.getByRole('checkbox', { name: '已停用分类', exact: true })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '最新上架', exact: true })).toBeDisabled()
    await screen.getByRole('checkbox', { name: '家居用品', exact: true }).tap()
    await expect(committed).toContainText('全部分类')
    await screen.getByRole('button', { name: '取消筛选', exact: true }).tap()
    await expect(products).toHaveCount(4)
    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await expect(screen.getByRole('checkbox', { name: '家居用品', exact: true })).toHaveAttribute('aria-checked', 'false')
    await screen.getByRole('checkbox', { name: '暂不可配送分类', exact: true }).tap()
    await screen.getByRole('button', { name: '应用商品筛选', exact: true }).tap()
    await expect(screen.getByText('应用拒绝：此分类暂不可配送。草稿已保留，结果未改变。', { exact: true })).toBeVisible()
    await expect(committed).toContainText('全部分类')
    await expect(screen.getByRole('checkbox', { name: '暂不可配送分类', exact: true })).toHaveAttribute('aria-checked', 'true')
    await screen.getByRole('button', { name: '重置草稿', exact: true }).tap()
    await expect(screen.getByRole('button', { name: '应用商品筛选', exact: true })).toBeDisabled()
    await screen.getByRole('checkbox', { name: '家居用品', exact: true }).tap()
    await screen.getByRole('button', { name: '价格从高到低', exact: true }).tap()
    await screen.getByRole('button', { name: '仅看有货', exact: true }).tap()
    await screen.getByRole('button', { name: '应用商品筛选', exact: true }).tap()
    await expect(result(miniProgram, 'filters')).toContainText('应用已接受筛选；本地结果：1 件')
    await expect(products).toHaveCount(1)
    await expect(products.first()).toContainText('云感午休毯')
    await expect(committed).toContainText('price-desc / home / 0–50000 分 / in-stock')

    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await miniProgram.commitNumber('//input[@aria-label="筛选最高价格"]', 5000)
    await miniProgram.commitNumber('//input[@aria-label="筛选最低价格"]', 10000)
    await expect(screen.getByRole('button', { name: '应用商品筛选', exact: true })).toBeDisabled()
    await expect(screen.getByText(/最低价格不能高于最高价格/)).toBeVisible()
    await miniProgram.commitNumber('//input[@aria-label="筛选最低价格"]', 0)
    await screen.getByRole('button', { name: '应用商品筛选', exact: true }).tap()
    await expect(products).toHaveCount(0)
    await expect(screen.getByText('没有符合条件的本地商品', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await screen.getByRole('button', { name: '重置草稿', exact: true }).tap()
    await screen.getByRole('button', { name: '应用商品筛选', exact: true }).tap()
    await expect(products).toHaveCount(4)
  })

  const stateCases = [
    { tab: '优惠券示例', action: '领取 新人券', loading: '正在加载优惠券…', empty: '暂无优惠券', error: '本地优惠数据读取失败；保留原有券供核对。' },
    { tab: '凭证示例', action: '申请退款', loading: '正在加载凭证…', empty: '暂无凭证', error: '本地凭证读取失败，保留现有订单证据。' },
    { tab: '评价示例', action: '提交评价', loading: '正在加载评价…', empty: '暂无评价', error: '本地评价读取失败；现有内容仍可核对。' },
    { tab: '收藏示例', action: '将 云感午休毯 加入购物车', loading: '正在加载收藏…', empty: '暂无收藏', error: '本地收藏读取失败，保留已知成员。' },
    { tab: '比较示例', action: '移出比较 云感午休毯', loading: '正在加载比较…', empty: '暂无比较商品', error: '本地比较读取失败，保留已知商品和字段。' },
  ]
  for (const scenario of stateCases) {
    test(`${scenario.tab}: loading, empty, error, disabled, busy and long content`, async ({ miniProgram, screen }) => {
      await enter(miniProgram)
      if (scenario.tab !== '优惠券示例') { await screen.getByRole('button', { name: scenario.tab, exact: true }).tap() }
      await screen.getByRole('button', { name: '加载状态', exact: true }).tap()
      await expect(screen.getByText(scenario.loading, { exact: true })).toBeVisible()
      await expect(screen.getByRole('button', { name: scenario.action, exact: true })).toBeDisabled()
      await screen.getByRole('button', { name: '空数据状态', exact: true }).tap()
      await expect(screen.getByText(scenario.empty, { exact: true })).toBeVisible()
      await screen.getByRole('button', { name: '错误状态', exact: true }).tap()
      await expect(screen.getByText(scenario.error, { exact: true })).toBeVisible()
      for (const mode of ['禁用状态', '忙碌状态']) {
        await screen.getByRole('button', { name: mode, exact: true }).tap()
        await expect(screen.getByRole('button', { name: scenario.action, exact: true })).toBeDisabled()
      }
      await screen.getByRole('button', { name: '长内容状态', exact: true }).tap()
      await expect(screen.getByText(/订单与服务承诺请以真实商家的确认结果为准。/).first()).toBeVisible()
      await expect(screen.getByRole('button', { name: scenario.action, exact: true })).toBeEnabled()
    })
  }

  test('filters: loading, empty, error, long choices and busy/disabled cancellation stays available', async ({ miniProgram, screen }) => {
    await enter(miniProgram)
    await screen.getByRole('button', { name: '筛选示例', exact: true }).tap()
    for (const mode of ['加载状态', '禁用状态', '忙碌状态']) {
      await screen.getByRole('button', { name: mode, exact: true }).tap()
      await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
      await expect(screen.getByRole('button', { name: '价格从低到高', exact: true })).toBeDisabled()
      await expect(screen.getByRole('button', { name: '取消筛选', exact: true })).toBeEnabled()
      await screen.getByRole('button', { name: '取消筛选', exact: true }).tap()
    }
    await screen.getByRole('button', { name: '空数据状态', exact: true }).tap()
    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await expect(screen.getByText('暂无分类选项', { exact: true })).toBeVisible()
    await expect(screen.getByText('暂无排序选项', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '取消筛选', exact: true }).tap()
    await screen.getByRole('button', { name: '错误状态', exact: true }).tap()
    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await expect(screen.getByText('本地筛选选项读取失败，保留已有草稿。', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '取消筛选', exact: true }).tap()
    await screen.getByRole('button', { name: '长内容状态', exact: true }).tap()
    await screen.getByRole('button', { name: '打开商品筛选', exact: true }).tap()
    await expect(screen.getByRole('checkbox', { name: /家居用品：这是用于阅读边界/ })).toBeVisible()
    await screen.getByRole('button', { name: '取消筛选', exact: true }).tap()
  })
})
