import { expect } from 'e2e'
import { classXPath, expectRoute, nativePlatforms, test } from './fixtures'

const stateXPath = '//*[@data-source-demo="state"]'
const composerXPath = '//textarea[@placeholder="给 Agent 发送消息…"]'
const retrievalXPath = classXPath('agent-retrieval')
const receiptsXPath = classXPath('agent-source-receipt')

test.describe('native B2 Source Chat', { platforms: nativePlatforms, requires: ['miniProgram'] }, () => {
  test.beforeEach(async ({ miniProgram }) => {
    await miniProgram.reLaunch('/pages/source-chat/index')
    await expectRoute(miniProgram, '/pages/source-chat/index')
    await expect(miniProgram.locator(stateXPath)).toContainText('response=idle;')
  })
  test.afterEach(async ({ miniProgram }) => { expect(await miniProgram.errors()).toEqual([]) })

  test('source availability and connection require explicit scope selection', async ({ miniProgram, screen }) => {
    const state = miniProgram.locator(stateXPath)
    const input = miniProgram.locator(composerXPath)
    await expect(screen.getByRole('button', { name: '创建工单' })).toBeDisabled()
    await screen.getByRole('button', { name: '停用本地知识库' }).tap()
    await expect(state).toContainText('scope=none;')
    await expect(input).toBeDisabled()
    await expect(miniProgram.locator('//*[@data-source-response="idle"]')).toContainText('请先连接并启用至少一个可用来源')
    await screen.getByRole('button', { name: '启用本地知识库' }).tap()
    await expect(input).toBeEnabled()
    await screen.getByRole('button', { name: '模拟来源不可用' }).tap()
    await expect(state).toContainText('scope=none;')
    await expect(screen.getByRole('button', { name: '连接本地知识库' })).toBeEnabled()
    await expect(input).toBeDisabled()
    await screen.getByRole('button', { name: '恢复演示来源' }).tap()
    await expect(state).toContainText('scope=none;')
    await screen.getByRole('button', { name: '启用本地知识库' }).tap()
    await screen.getByRole('button', { name: '连接演示归档' }).tap()
    await expect(state).toContainText('connections=1;')
    await expect(screen.getByRole('button', { name: '连接演示归档' })).toHaveCount(0)
    await expect(miniProgram.locator(classXPath('agent-composer-scope'))).toContainText('连接中')
    await screen.getByRole('button', { name: '完成演示连接' }).tap()
    await expect(state).toContainText('scope=handbook;')
    await expect(screen.getByRole('button', { name: '完成演示连接' })).toBeDisabled()
    await screen.getByRole('button', { name: '禁用操作' }).tap()
    await expect(screen.getByRole('button', { name: '启用演示归档' })).toBeDisabled()
    await expect(input).toBeDisabled()
    await expect(state).toContainText('toggles=3;')
    await expect(state).toContainText('submits=0;')
    await screen.getByRole('button', { name: '启用操作' }).tap()
    await screen.getByRole('button', { name: '启用演示归档' }).tap()
    await expect(state).toContainText('scope=handbook,archive;')
    await expect(state).toContainText('toggles=4;')
  })

  test('retrieval progress settles into visible receipts and application-opened citations', async ({ miniProgram, screen }) => {
    const state = miniProgram.locator(stateXPath)
    const input = miniProgram.locator(composerXPath)
    await input.fill('如何申请退货？')
    await miniProgram.locator(classXPath('agent-composer__submit')).tap()
    await expect(state).toContainText('response=retrieving;')
    await expect(input).toHaveValue('')
    await expect(miniProgram.locator(`${retrievalXPath}//*[@data-status="queued"]`)).toContainText('本地知识库')
    await expect(screen.getByRole('button', { name: '停用本地知识库' })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '连接演示归档' })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '创建工单' })).toBeDisabled()
    await screen.getByRole('button', { name: '演示读取' }).tap()
    await expect(miniProgram.locator(`${retrievalXPath}//*[@data-status="reading"]`)).toContainText('正在读取本地演示条目')
    await expect(screen.getByRole('button', { name: '演示读取' })).toBeDisabled()
    await screen.getByRole('button', { name: '演示成功' }).tap()
    await expect(state).toContainText('response=answered;')
    // Response state, receipt controls and local document preview use real native text.
    // This does not claim headless observation of AgentChat's rich-text message body.
    await expect(miniProgram.locator('//*[@data-source-response="answered"]')).toContainText('已提供有来源的回答')
    await expect(miniProgram.locator(`${receiptsXPath}//*[@data-status="read"]`)).toContainText('1 项')
    await screen.getByRole('button', { name: '查看本地知识库回执' }).tap()
    await expect(state).toContainText('receipts=1;')
    await expect(miniProgram.locator('//*[@data-source-demo="document"]')).toContainText('实际政策由商家确认')
    await miniProgram.locator(classXPath('agent-citations__item')).tap()
    await expect(state).toContainText('citations=1;')
    await expect(miniProgram.locator('//*[@data-source-demo="document"]')).toContainText('本地演示原文：签收后七天内可申请退货')
    await screen.getByRole('button', { name: '禁用操作' }).tap()
    await expect(miniProgram.locator(receiptsXPath)).toContainText('本地知识库回执')
    await expect(miniProgram.locator(classXPath('agent-citations__item'))).toBeVisible()
    await expect(miniProgram.locator(classXPath('agent-citations__item'))).toBeDisabled()
    await expect(screen.getByRole('button', { name: '查看本地知识库回执' })).toBeDisabled()
    await expect(state).toContainText('citations=1;receipts=1;tickets=0')
    if (miniProgram.mode === 'devtools') { await miniProgram.screenshot('source-chat-disabled-evidence') }
  })

  test('failure retry, empty and out-of-scope results emit one ticket intent per application grant', async ({ miniProgram, screen }) => {
    const state = miniProgram.locator(stateXPath)
    const request = miniProgram.locator('//*[@data-source-demo="ticket"]')
    await miniProgram.locator(composerXPath).fill('没有找到退货资料')
    await miniProgram.locator(classXPath('agent-composer__submit')).tap()
    await screen.getByRole('button', { name: '演示失败' }).tap()
    await expect(screen.getByRole('alert')).toContainText('检索失败，尚未生成回答')
    await expect(miniProgram.locator(`${receiptsXPath}//*[@data-status="failed"]`)).toContainText('演示读取失败')
    await expect(miniProgram.locator(classXPath('agent-citations__item'))).toHaveCount(0)
    await screen.getByRole('button', { name: '禁用操作' }).tap()
    await expect(screen.getByRole('button', { name: '重试本地知识库' })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '连接本地知识库回执' })).toBeDisabled()
    await expect(screen.getByRole('button', { name: '创建工单' })).toBeDisabled()
    await expect(state).toContainText('tickets=0')
    await screen.getByRole('button', { name: '启用操作' }).tap()
    await screen.getByRole('button', { name: '连接本地知识库回执' }).tap()
    await expect(state).toContainText('connections=1;')
    await expect(screen.getByRole('alert')).toContainText('演示没有执行连接')
    await screen.getByRole('button', { name: '创建工单' }).tap()
    await expect(request).toContainText('转交申请（未创建工单）：没有找到退货资料；原因=failed；来源=handbook')
    await expect(screen.getByRole('button', { name: '创建工单' })).toBeDisabled()
    await screen.getByRole('button', { name: '停用本地知识库' }).tap()
    await expect(screen.getByRole('button', { name: '重试本地知识库' })).toHaveCount(0)
    await expect(miniProgram.locator(`${retrievalXPath}//*[@data-status="failed"]`)).toBeVisible()
    await expect(state).toContainText('submits=1;')
    await screen.getByRole('button', { name: '启用本地知识库' }).tap()
    await screen.getByRole('button', { name: '重试本地知识库' }).tap()
    await expect(state).toContainText('response=retrieving;')
    await expect(state).toContainText('submits=2;')
    await screen.getByRole('button', { name: '演示空结果' }).tap()
    await expect(miniProgram.locator('//*[@data-source-response="empty"]')).toContainText('没有找到相关内容')
    await expect(miniProgram.locator(`${receiptsXPath}//*[@data-status="read"]`)).toContainText('0 项')
    await screen.getByRole('button', { name: '创建工单' }).tap()
    await expect(request).toContainText('原因=empty；来源=handbook')
    await expect(state).toContainText('tickets=2')
    await miniProgram.locator(composerXPath).fill('查询财务系统')
    await miniProgram.locator(classXPath('agent-composer__submit')).tap()
    await screen.getByRole('button', { name: '演示超出范围' }).tap()
    await expect(miniProgram.locator('//*[@data-source-response="out-of-scope"]')).toContainText('问题超出当前知识范围')
    await expect(miniProgram.locator(`${receiptsXPath}//*[@data-status="skipped"]`)).toBeVisible()
    await expect(miniProgram.locator(classXPath('agent-citations__item'))).toHaveCount(0)
    await screen.getByRole('button', { name: '创建工单' }).tap()
    await expect(request).toContainText('查询财务系统；原因=out-of-scope；来源=handbook')
    await expect(state).toContainText('tickets=3')
    await expect(screen.getByRole('button', { name: '创建工单' })).toBeDisabled()
  })

  test('unbound prompt survives submit and disabled stop remains a cancellation escape', async ({ miniProgram, screen }) => {
    const state = miniProgram.locator(stateXPath)
    await screen.getByRole('button', { name: '切换为非受控输入' }).tap()
    await expect(state).toContainText('mode=uncontrolled;')
    await miniProgram.locator(composerXPath).fill('组件保留的本地草稿')
    await miniProgram.locator(classXPath('agent-composer__submit')).tap()
    await expect(state).toContainText('response=retrieving;')
    await expect(miniProgram.locator('//*[@data-source-demo="question"]')).toContainText('组件保留的本地草稿')
    await screen.getByRole('button', { name: '禁用操作' }).tap()
    await expect(miniProgram.locator(composerXPath)).toBeDisabled()
    await screen.getByRole('button', { name: '停止生成' }).tap()
    await expect(state).toContainText('response=idle;')
    await expect(miniProgram.locator(`${retrievalXPath}//*[@data-status="skipped"]`)).toContainText('应用已停止本地演示检索')
    await expect(screen.getByRole('button', { name: '停止生成' })).toHaveCount(0)
    await expect(miniProgram.locator(composerXPath)).toHaveValue('组件保留的本地草稿')
    await screen.getByRole('button', { name: '启用操作' }).tap()
    await screen.getByRole('button', { name: '切换为受控输入' }).tap()
    await expect(state).toContainText('mode=controlled;')
    await expect(miniProgram.locator(composerXPath)).toHaveValue('')
    await expect(miniProgram.locator(classXPath('agent-composer__submit'))).toBeDisabled()
  })
})
