packages:
  - apps/*
  - packages/*
  - examples/*

autoInstallPeers: false

minimumReleaseAge: 0
overrides:
  undici: 7.29.1

versioning:
  fixed:
    - ['@varo-ui/ai', '@varo-ui/cli', '@varo-ui/h5', '@varo-ui/headless', '@varo-ui/theme', '@varo-ui/weapp']
  changelog:
    storage: repository

allowBuilds:
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  '@tailwindcss/oxide': true
  sharp: true
  vue-demi: true
  workerd: true
  '@parcel/watcher': true

patchedDependencies:
  '@devframes/agentic@1.2.3': patches/@devframes__agentic@1.2.3.patch
  '@e2e-dev/web@0.13.0': patches/@e2e-dev__web@0.13.0.patch
  devframe@1.2.3: patches/devframe@1.2.3.patch
