import { expect } from 'e2e'
import { test } from '../../engines/web'

test.describe('H5 B4 Application Blocks', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/?demo=application-blocks')
    await expect(browser.locator('#application-blocks-demo')).toContainText('Labelled in-memory data only.')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('settings accept controlled changes and preserve rejected values', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    const notifications = demo.getByRole('switch', { name: 'Local notifications', exact: true })
    await expect(notifications).toHaveAttribute('aria-checked', 'false')
    await notifications.click()
    await expect(notifications).toHaveAttribute('aria-checked', 'true')
    await expect(demo.getByRole('switch', { name: 'Managed setting', exact: true })).toBeDisabled()
    await expect(demo.getByRole('switch', { name: 'Pending setting', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Density: Unavailable', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Density: Dense', exact: true }).click()
    await expect(demo).toContainText('Local preference rejected; value preserved')
    await expect(demo.getByRole('button', { name: 'Density: Comfortable', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await demo.getByRole('button', { name: 'Density: Compact', exact: true }).click()
    await expect(demo).toContainText('Local preference updated: density=compact')
    await expect(demo.getByRole('button', { name: 'Density: Compact', exact: true })).toBeDisabled()
  })

  test('onboarding bounds navigation and keeps close available while pending', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('button', { name: 'Demo: Onboarding', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Back', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Next onboarding step', exact: true }).click()
    await expect(demo).toContainText('Step 2 of 2')
    await expect(demo.getByRole('button', { name: 'Finish onboarding', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(demo).toContainText('Step 1 of 2')
    await demo.getByRole('switch', { name: 'Show pending state', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Next onboarding step', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Close onboarding', exact: true }).click()
    await expect(demo).toContainText('Local guide closed without completion')
    await demo.getByRole('switch', { name: 'Show pending state', exact: true }).click()
    await demo.getByRole('button', { name: 'Reopen local guide', exact: true }).click()
    await demo.getByRole('button', { name: 'Next onboarding step', exact: true }).click()
    await demo.getByRole('switch', { name: 'I reviewed the local guide', exact: true }).click()
    await demo.getByRole('button', { name: 'Finish onboarding', exact: true }).click()
    await expect(demo).toContainText('Local guide completed')
  })

  test('multi-step form validates preserves values and adds a real local summary row', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('button', { name: 'Demo: Form', exact: true }).click()
    await demo.getByRole('button', { name: 'Next form step', exact: true }).click()
    await expect(demo).toContainText('Enter an applicant name.')
    await expect(demo).toContainText('Choose a team.')
    await demo.getByPlaceholder('Enter a local applicant name').fill('Admin')
    await demo.getByRole('button', { name: 'Team: Design', exact: true }).click()
    await demo.getByRole('button', { name: 'Next form step', exact: true }).click()
    await expect(demo).toContainText('This name is reserved or already exists in the local application list.')
    await demo.getByPlaceholder('Enter a local applicant name').fill('Ada')
    await demo.getByRole('button', { name: 'Next form step', exact: true }).click()
    await expect(demo).toContainText('Step 2 of 2: Review and consent')
    await demo.getByRole('button', { name: 'Submit application', exact: true }).click()
    await expect(demo).toContainText('Consent is required for local processing.')
    await demo.getByRole('button', { name: 'Previous form step', exact: true }).click()
    await expect(demo.getByPlaceholder('Enter a local applicant name')).toHaveValue('Ada')
    await expect(demo.getByRole('button', { name: 'Team: Design', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await demo.getByRole('button', { name: 'Next form step', exact: true }).click()
    await demo.getByRole('switch', { name: 'Consent to local processing', exact: true }).click()
    await demo.getByRole('button', { name: 'Submit application', exact: true }).click()
    await expect(demo).toContainText('Local application saved: Ada')
    await demo.getByRole('button', { name: 'Submit application', exact: true }).click()
    await expect(demo).toContainText('This name is reserved or already exists in the local application list.')
    await demo.getByRole('button', { name: 'Demo: Summary', exact: true }).click()
    await expect(browser.locator('[data-summary-value="applications"]')).toHaveText('2')
    await expect(demo).toContainText('Ada')
    await demo.getByRole('button', { name: 'Period: This session', exact: true }).click()
    await expect(browser.locator('[data-summary-value="applications"]')).toHaveText('1')
  })

  test('timeline retry validates input and records the actual local import', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('button', { name: 'Demo: Timeline', exact: true }).click()
    await demo.getByRole('button', { name: 'Retry Local import', exact: true }).click()
    await expect(demo).toContainText('Enter a unique import name before retrying.')
    await demo.getByPlaceholder('Enter a unique import name').fill('Quinn')
    await demo.getByRole('button', { name: 'Retry Local import', exact: true }).click()
    await expect(demo).toContainText('Added Quinn to the local application list.')
    await expect(demo.getByRole('button', { name: 'Retry Local import', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: 'Details for Local import', exact: true }).click()
    await expect(browser.locator('#application-blocks-demo [data-application-result="timeline"]')).toContainText('Added Quinn')
    await demo.getByRole('button', { name: 'Demo: Summary', exact: true }).click()
    await expect(demo).toContainText('Quinn')
    await expect(browser.locator('[data-summary-value="applications"]')).toHaveText('2')
  })

  test('summary period error retry and empty states retain honest context', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('button', { name: 'Demo: Summary', exact: true }).click()
    await expect(demo).toContainText('River')
    await demo.getByRole('button', { name: 'Show local summary error', exact: true }).click()
    await expect(demo).toContainText('Local summary error example')
    await expect(demo).toContainText('River')
    await demo.getByRole('button', { name: 'Retry summary', exact: true }).click()
    await expect(demo).toContainText('Local summary acknowledgements: 1')
    await expect(demo.getByRole('button', { name: 'Retry summary', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: 'Period: This session', exact: true }).click()
    await expect(browser.locator('[data-summary-value="applications"]')).toHaveText('0')
    await demo.getByRole('switch', { name: 'Show empty data', exact: true }).click()
    await expect(demo).toContainText('No summary data')
  })

  test('booking rechecks local availability rejects conflicts and cancels accepted records', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('button', { name: 'Demo: Booking', exact: true }).click()
    await expect(demo.getByRole('button', { name: '09:00', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '11:00', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Request booking', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: '10:00', exact: true }).click()
    await demo.getByRole('button', { name: 'Reserve 10:00 in local ledger', exact: true }).click()
    await demo.getByRole('button', { name: 'Request booking', exact: true }).click()
    await expect(demo).toContainText('Local booking rejected; nothing booked for you')
    await expect(demo).toContainText('Local ledger rows: 1')
    await expect(demo.getByRole('button', { name: 'Request booking', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Sample day two', exact: true }).click()
    await demo.getByRole('button', { name: '14:00', exact: true }).click()
    await demo.getByRole('button', { name: 'Request booking', exact: true }).click()
    await expect(demo).toContainText('Local booking confirmed: 14:00')
    await expect(demo).toContainText('Local ledger rows: 2')
    await demo.getByRole('switch', { name: 'Show pending state', exact: true }).click()
    await demo.getByRole('button', { name: 'Cancel booking', exact: true }).click()
    await expect(demo).toContainText('Local booking cancelled; no external service called')
    await expect(demo).toContainText('Local ledger rows: 1')
  })

  test('people paging filters grants and confirmed mutations update local records', async ({ browser }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('button', { name: 'Demo: People', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Details for Casey', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: 'Load more people', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Details for Casey', exact: true })).toBeEnabled()
    await demo.getByRole('button', { name: 'Details for Rowan', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Remove Rowan', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Approve Rowan', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Close person details', exact: true }).click()
    await demo.getByRole('button', { name: 'People: Pending', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Details for Rowan', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: 'Details for Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Role: Reviewer', exact: true }).click()
    await expect(demo).toContainText('Local person updated: Maya (role)')
    await demo.getByRole('button', { name: 'Approve Maya', exact: true }).click()
    await expect(demo).toContainText('No people in this view')
    await demo.getByRole('button', { name: 'People: Active', exact: true }).click()
    await demo.getByRole('button', { name: 'Details for Maya', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Approve Maya', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Status: Inactive', exact: true }).click()
    await expect(demo).toContainText('Local person updated: Maya (status)')
    await demo.getByRole('button', { name: 'People: All', exact: true }).click()
    await demo.getByRole('button', { name: 'Details for Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Remove Maya', exact: true }).click()
    await expect(demo.getByRole('group', { name: 'Confirm local removal', exact: true })).toContainText('Maya')
    await demo.getByRole('button', { name: 'People: Active', exact: true }).click()
    await demo.getByRole('button', { name: 'Details for Rowan', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Confirm local removal', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: 'People: All', exact: true }).click()
    await demo.getByRole('button', { name: 'Details for Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Remove Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Close person details', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Confirm local removal', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: 'Details for Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Remove Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Keep local person', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Remove Maya', exact: true })).toBeEnabled()
    await demo.getByRole('button', { name: 'Remove Maya', exact: true }).click()
    await demo.getByRole('button', { name: 'Confirm local removal', exact: true }).click()
    await expect(demo).toContainText('Removed Maya from the local list')
    await expect(demo.getByRole('button', { name: 'Details for Maya', exact: true })).toHaveCount(0)
  })

  test('injected disabled pending and empty states preserve evidence without mutations', async ({ browser, app }) => {
    const demo = browser.locator('#application-blocks-demo')
    await demo.getByRole('switch', { name: 'Disable mutations', exact: true }).click()
    await expect(demo.getByRole('switch', { name: 'Local notifications', exact: true })).toBeDisabled()
    await expect(demo).toContainText('No preference changes')
    await demo.getByRole('switch', { name: 'Disable mutations', exact: true }).click()
    await demo.getByRole('switch', { name: 'Show pending state', exact: true }).click()
    await expect(demo).toContainText('Local preview account')
    await expect(demo.getByRole('button', { name: 'Density: Compact', exact: true })).toBeDisabled()
    await demo.getByRole('switch', { name: 'Show pending state', exact: true }).click()
    await demo.getByRole('switch', { name: 'Show empty data', exact: true }).click()
    for (const [panel, text] of [['Settings', 'No settings available'], ['Onboarding', 'No onboarding step available'], ['Form', 'No form step available'], ['Timeline', 'No history yet'], ['Summary', 'No summary data'], ['Booking', 'No dates available'], ['People', 'No people in this view']]) {
      await demo.getByRole('button', { name: `Demo: ${panel}`, exact: true }).click()
      await expect(demo).toContainText(text)
    }
    await app.screenshot('h5-application-empty-people')
  })
})
