import { expect } from 'e2e'
import { test } from '../../engines/web'

test.describe('H5 B1 Chat Blocks', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('real long-context submit can be stopped from the sheet', async ({ app, browser, screen }) => {
    await screen.getByRole('button', { name: '引用长段落', exact: true }).click()
    const state = browser.locator('[data-chat-demo="state"]')
    await expect(state).toContainText('context=long-passage;open=true;')
    const dialog = screen.getByRole('dialog')
    const title = await browser.locator('[role="dialog"] h2').textContent()
    expect(title).not.toBeNull()
    await expect(screen.getByRole('dialog', { name: title!.trim(), exact: true })).toBeVisible()
    await dialog.getByRole('textbox').fill('请整理这段引用，保留段落顺序并说明每步依据。\n'.repeat(16))
    await dialog.getByRole('button', { name: '发送', exact: true }).click()
    await expect(state).toContainText('status=streaming;')
    const readViewport = () => browser.evaluate(() => {
      const viewport = document.querySelector<HTMLElement>('[role="dialog"] .agent-chat__viewport')
      if (!viewport) { throw new Error('Missing assistant conversation viewport') }
      return { top: viewport.scrollTop, height: viewport.clientHeight, content: viewport.scrollHeight }
    })
    await expect.poll(async () => {
      const viewport = await readViewport()
      return viewport.content - viewport.height
    }).toBeGreaterThan(64)
    const following = await readViewport()
    await expect.poll(async () => (await readViewport()).content).toBeGreaterThan(following.content)
    await expect.poll(async () => {
      const viewport = await readViewport()
      return viewport.content - viewport.height - viewport.top
    }).toBeLessThanOrEqual(1)
    await browser.locator('[role="dialog"] .agent-chat__viewport').hover()
    await browser.mouse.wheel(0, -following.content)
    await expect.poll(async () => (await readViewport()).top).toBeLessThanOrEqual(1)
    const reading = await readViewport()
    await expect.poll(async () => (await readViewport()).content).toBeGreaterThan(reading.content)
    expect((await readViewport()).top).toBeCloseTo(reading.top, 0)
    await app.screenshot('h5-chat-preserved-reading-position')
    await dialog.getByRole('button', { name: '停止生成', exact: true }).click()
    await expect(state).toContainText('status=cancelled;')
    await expect(state).toContainText('action=stopped')
    await expect(dialog.getByRole('button', { name: '停止生成', exact: true })).toHaveCount(0)
    await app.screenshot('h5-chat-long-context-stopped')
  })

  test('pre-message failure remains visible and retry produces a real response', async ({ app, browser }) => {
    const demo = browser.locator('#chat-blocks-demo')
    const state = browser.locator('[data-chat-demo="state"]')
    await demo.getByRole('button', { name: '演示错误', exact: true }).click()
    await expect(state).toContainText('status=failed;')
    await expect(demo.getByRole('alert')).toContainText('演示错误：请重试本地生成。')
    await app.screenshot('h5-chat-pre-message-error')
    await demo.getByRole('button', { name: '重试', exact: true }).click()
    await expect(state).toContainText('status=completed;')
    await expect(demo.getByRole('alert')).toHaveCount(0)
    await expect(browser.locator('#chat-blocks-demo .agent-stream')).toContainText('建议草稿：先说明目标')
  })

  test('history and new conversation preserve controlled input and disabled behavior', async ({ app, browser }) => {
    const demo = browser.locator('#chat-blocks-demo')
    const state = browser.locator('[data-chat-demo="state"]')
    const composer = browser.locator('#chat-blocks-demo .agent-composer textarea')
    await demo.getByRole('button', { name: '已保存的写作建议', exact: true }).click()
    await expect(state).toContainText('history=saved;')
    await expect(demo).toContainText('先写清楚目标，再说明下一步。')
    await demo.getByRole('button', { name: '新建会话', exact: true }).click()
    await expect(state).toContainText('history=new;')
    await expect(composer).toHaveValue('')
    await demo.getByRole('button', { name: '切换页面布局', exact: true }).click()
    await expect(browser.locator('#chat-blocks-demo [data-layout="page"]')).toBeVisible()
    await demo.getByRole('button', { name: '禁用输入', exact: true }).click()
    await expect(composer).toBeDisabled()
    await demo.getByRole('button', { name: '启用输入', exact: true }).click()
    await expect(composer).toBeEnabled()
    await app.screenshot('h5-chat-page-layout')
  })

  test('sheet context, expand/back/close and explicit insertion preserve the draft', async ({ app, browser, screen }) => {
    const state = browser.locator('[data-chat-demo="state"]')
    const draft = browser.locator('[data-chat-demo="draft"]')
    const initialDraft = await browser.evaluate(() => document.querySelector('[data-chat-demo="draft"]')?.textContent ?? null)
    expect(initialDraft).not.toBeNull()
    await screen.getByRole('button', { name: '引用此段', exact: true }).click()
    await expect(state).toContainText('context=passage;open=true;')
    await expect(draft).toHaveText(initialDraft!)
    await screen.getByRole('button', { name: '移除引用', exact: true }).click()
    await expect(state).toContainText('context=none;')
    await screen.getByRole('button', { name: '展开助手', exact: true }).click()
    await expect(state).toContainText('expanded=true;')
    await app.screenshot('h5-assistant-expanded')
    await screen.getByRole('button', { name: '返回助手面板', exact: true }).click()
    await expect(state).toContainText('expanded=false;')
    await screen.getByRole('button', { name: '已保存的写作建议', exact: true }).click()
    await expect(draft).toHaveText(initialDraft!)
    await screen.getByRole('button', { name: '插入到草稿', exact: true }).click()
    await expect(state).toContainText('inserts=1;action=inserted:saved-answer')
    await expect(draft).toContainText('先写清楚目标，再说明下一步。')
    await screen.getByRole('button', { name: '关闭助手', exact: true }).click()
    await expect(state).toContainText('open=false;')
    await screen.getByRole('button', { name: '打开助手', exact: true }).click()
    await expect(state).toContainText('open=true;')
    await expect(draft).toContainText('先写清楚目标，再说明下一步。')
    await app.screenshot('h5-assistant-inserted-reopened')
  })
})
