import { expect } from 'e2e'
import { test } from '../../engines/web'

test.describe('H5 B5 mobile data workspace', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/?demo=data-workspace')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('chart derives values shows zero and detail accepts twelve and rejects thirteen categories', async ({ app, browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    await expect(browser.locator('[data-chart-id="todo"]')).toContainText('To do: 8 planned hours')
    await expect(browser.locator('[data-chart-id="doing"]')).toContainText('In progress: 2 planned hours')
    await expect(browser.locator('[data-chart-id="done"]')).toContainText('Done: 0 planned hours')
    await demo.getByRole('button', { name: 'Inspect To do', exact: true }).click()
    await expect(browser.locator('[data-chart-detail]')).toContainText('Planned hours summed from local task records')
    await expect(demo.getByRole('button', { name: 'Inspect To do', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Toggle twelve categories', exact: true }).click()
    await expect(browser.locator('[data-chart-id]')).toHaveCount(12)
    await expect(browser.locator('[data-chart-id="unassigned-11"]')).toContainText('long label that remains readable on mobile: 0 planned hours')
    await app.screenshot('h5-data-chart-twelve-categories')
    await demo.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).click()
    await expect(demo).toContainText('Chart configuration rejected: at most 12 categories')
    await expect(browser.locator('[data-chart-id]')).toHaveCount(0)
    await demo.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).click()
    await expect(browser.locator('[data-chart-id]')).toHaveCount(12)
  })

  test('schedule bounds day week navigation and disabled dates preserve controlled selection', async ({ browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    await demo.getByRole('button', { name: 'Demo: Schedule', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Previous period', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Choose date 2026-10-10', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Choose Gamma planning slot', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Day view', exact: true }).click()
    await expect(browser.locator('[data-schedule-date]')).toHaveCount(1)
    await demo.getByRole('button', { name: 'Next period', exact: true }).click()
    await demo.getByRole('button', { name: 'Choose date 2026-10-09', exact: true }).click()
    await expect(browser.locator('[data-schedule-selection]')).toContainText('2026-10-09')
    await demo.getByRole('button', { name: 'Week view', exact: true }).click()
    await demo.getByRole('button', { name: 'Next period', exact: true }).click()
    await expect(browser.locator('[data-schedule-view]')).toContainText('2026-10-16')
    await expect(demo.getByRole('button', { name: 'Next period', exact: true })).toBeDisabled()
    await expect(browser.locator('[data-schedule-selection]')).toContainText('2026-10-09')
    await demo.getByRole('button', { name: 'Previous period', exact: true }).click()
    await demo.getByRole('button', { name: 'Previous period', exact: true }).click()
    await expect(browser.locator('[data-schedule-view]')).toContainText('2026-10-08')
    await expect(demo.getByRole('button', { name: 'Previous period', exact: true })).toBeDisabled()
  })

  test('schedule rejects occupied slots applies date filters and retains unavailable selection', async ({ browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    await demo.getByRole('button', { name: 'Demo: Schedule', exact: true }).click()
    await demo.getByRole('button', { name: 'Toggle Alpha ledger conflict', exact: true }).click()
    await demo.getByRole('button', { name: 'Choose Alpha planning slot', exact: true }).click()
    await expect(demo).toContainText('Local slot rejected: Alpha is occupied')
    await expect(browser.locator('[data-workspace-result="schedule"]')).toContainText('No local slot chosen')
    await demo.getByRole('button', { name: 'Choose Beta planning slot', exact: true }).click()
    await expect(browser.locator('[data-workspace-result="schedule"]')).toContainText('Local slot chosen: Beta on 2026-10-09')
    await demo.getByRole('button', { name: 'Make selected date unavailable', exact: true }).click()
    await expect(demo).toContainText('Selected date is no longer available')
    await expect(browser.locator('[data-schedule-selection]')).toContainText('2026-10-09')
    await demo.getByRole('button', { name: 'Demo: Grid', exact: true }).click()
    await demo.getByRole('button', { name: 'Filter grid to selected date', exact: true }).click()
    await expect(browser.locator('[data-grid-record]')).toHaveCount(1)
    await expect(browser.locator('[data-grid-record="beta"]')).toContainText('Beta')
    await expect(browser.locator('[data-grid-date-filter]')).toContainText('2026-10-09')
    await demo.getByRole('button', { name: 'Clear date filter', exact: true }).click()
    await expect(browser.locator('[data-grid-page]')).toContainText('4 records')
  })

  test('board allowed rejected and approved moves change cards and derived chart totals', async ({ app, browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    await demo.getByRole('button', { name: 'Demo: Board', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Move Alpha to To do', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Move Beta to Done', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Move Gamma to In progress', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Move Alpha to In progress', exact: true }).click()
    await expect(browser.locator('[data-board-column="doing"] [data-board-card="alpha"]')).toHaveCount(1)
    await demo.getByRole('button', { name: 'Move Alpha to Done', exact: true }).click()
    await expect(demo).toContainText('Move rejected: approve this task before Done')
    await expect(browser.locator('[data-board-column="doing"] [data-board-card="alpha"]')).toHaveCount(1)
    await expect(browser.locator('[data-board-column="done"] [data-board-card="alpha"]')).toHaveCount(0)
    await demo.getByRole('button', { name: 'Approve Alpha', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Approve Alpha', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Inspect Alpha', exact: true }).click()
    await expect(browser.locator('[data-board-detail]')).toContainText('Approved')
    await demo.getByRole('button', { name: 'Move Alpha to Done', exact: true }).click()
    await expect(browser.locator('[data-board-column="done"] [data-board-card="alpha"]')).toHaveCount(1)
    await app.screenshot('h5-data-board-approved-move')
    await demo.getByRole('button', { name: 'Demo: Chart', exact: true }).click()
    await expect(browser.locator('[data-chart-id="todo"]')).toContainText('To do: 5 planned hours')
    await expect(browser.locator('[data-chart-id="done"]')).toContainText('Done: 3 planned hours')
  })

  test('grid preserves base columns expansion filtering grouping and bounded pages', async ({ browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    await demo.getByRole('button', { name: 'Demo: Grid', exact: true }).click()
    await expect(browser.locator('[data-grid-record]')).toHaveCount(2)
    await expect(demo.getByRole('button', { name: 'Previous records', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Column: Hours', exact: true }).click()
    await expect(browser.locator('[data-grid-cell="hours"]')).toHaveCount(0)
    await expect(browser.locator('[data-grid-record="alpha"]')).toContainText('Alpha')
    await demo.getByRole('button', { name: 'Column: Hours', exact: true }).click()
    await expect(browser.locator('[data-grid-record="alpha"]')).toContainText('Hours: 3')
    await demo.getByRole('button', { name: 'Expand Alpha', exact: true }).click()
    await expect(browser.locator('[data-grid-record="alpha"] [data-grid-detail]')).toContainText('Alpha planning on 2026-10-08')
    await demo.getByRole('button', { name: 'Collapse Alpha', exact: true }).click()
    await expect(browser.locator('[data-grid-detail]')).toHaveCount(0)
    await demo.getByRole('button', { name: 'Group records', exact: true }).click()
    await expect(browser.locator('[data-grid-group]')).toHaveCount(2)
    await expect(demo).toContainText('Owner: Avery')
    await demo.getByPlaceholder('Filter local records').fill('Bo')
    await expect(browser.locator('[data-grid-record="alpha"]')).toHaveCount(0)
    await expect(browser.locator('[data-grid-record="beta"]')).toHaveCount(1)
    await expect(browser.locator('[data-grid-record="delta"]')).toHaveCount(1)
    await expect(browser.locator('[data-grid-group]')).toHaveCount(1)
    await demo.getByPlaceholder('Filter local records').fill('no match')
    await expect(demo).toContainText('No matching records')
    await demo.getByPlaceholder('Filter local records').fill('')
    await demo.getByRole('button', { name: 'Next records', exact: true }).click()
    await expect(browser.locator('[data-grid-page]')).toContainText('Page 2 of 2')
    await expect(demo.getByRole('button', { name: 'Edit Gamma', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Next records', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Previous records', exact: true }).click()
    await expect(browser.locator('[data-grid-record="alpha"]')).toHaveCount(1)
  })

  test('grid editing preserves drafts on field and application rejection then updates real records', async ({ app, browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    await demo.getByRole('button', { name: 'Demo: Grid', exact: true }).click()
    await demo.getByRole('button', { name: 'Edit Alpha', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Save record', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Next records', exact: true })).toBeDisabled()
    await demo.getByPlaceholder('Edit Hours').fill('9')
    await demo.getByRole('button', { name: 'Save record', exact: true }).click()
    await expect(demo).toContainText('Hours must be an integer from 0 to 8.')
    await expect(browser.locator('[data-grid-record="alpha"]')).toContainText('Hours: 3')
    await demo.getByPlaceholder('Edit Hours').fill('4')
    await demo.getByPlaceholder('Edit Title').fill('Beta')
    await demo.getByRole('button', { name: 'Save record', exact: true }).click()
    await expect(demo).toContainText('Save rejected: another local record already uses this title.')
    await expect(demo.getByPlaceholder('Edit Title')).toHaveValue('Beta')
    await demo.getByPlaceholder('Edit Title').fill('Alpha revised')
    await demo.getByRole('button', { name: 'Save record', exact: true }).click()
    await expect(browser.locator('[data-grid-record="alpha"]')).toContainText('Alpha revised')
    await expect(browser.locator('[data-grid-record="alpha"]')).toContainText('Hours: 4')
    await expect(demo.getByPlaceholder('Edit Title')).toHaveCount(0)
    await app.screenshot('h5-data-grid-accepted-edit')
    await demo.getByRole('button', { name: 'Edit Alpha revised', exact: true }).click()
    await demo.getByRole('button', { name: 'Toggle busy', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Save record', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Cancel edit', exact: true }).click()
    await expect(demo.getByPlaceholder('Edit Title')).toHaveCount(0)
    await demo.getByRole('button', { name: 'Toggle busy', exact: true }).click()
    await demo.getByRole('button', { name: 'Demo: Chart', exact: true }).click()
    await expect(browser.locator('[data-chart-id="todo"]')).toContainText('To do: 9 planned hours')
  })

  test('all blocks retain evidence across disabled loading busy error empty and invalid states', async ({ browser }) => {
    const demo = browser.locator('#data-workspace-demo')
    for (const [panel, action, emptyText, invalidText] of [
      ['Chart', 'Inspect To do', 'No chart data', 'at most 12 categories'],
      ['Schedule', 'Next period', 'No events on this date', 'valid ISO dates'],
      ['Board', 'Move Alpha to In progress', 'No cards in this column', 'at most 50 cards'],
      ['Grid', 'Edit Alpha', 'No matching records', 'page size 1–50'],
    ] as const) {
      await demo.getByRole('button', { name: `Demo: ${panel}`, exact: true }).click()
      for (const state of ['disabled', 'loading', 'busy']) {
        await demo.getByRole('button', { name: `Toggle ${state}`, exact: true }).click()
        await expect(demo.getByRole('button', { name: action, exact: true })).toBeDisabled()
        await demo.getByRole('button', { name: `Toggle ${state}`, exact: true }).click()
        await expect(demo.getByRole('button', { name: action, exact: true })).toBeEnabled()
      }
      await demo.getByRole('button', { name: 'Toggle application error', exact: true }).click()
      await expect(demo).toContainText('Injected local application error; existing data is retained.')
      await expect(demo.getByRole('button', { name: action, exact: true })).toBeEnabled()
      await demo.getByRole('button', { name: 'Toggle application error', exact: true }).click()
      await demo.getByRole('button', { name: 'Toggle empty', exact: true }).click()
      await expect(demo).toContainText(emptyText)
      await demo.getByRole('button', { name: 'Toggle empty', exact: true }).click()
      await demo.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).click()
      await expect(demo).toContainText(invalidText)
      await demo.getByRole('button', { name: 'Toggle invalid configuration', exact: true }).click()
      await expect(demo.getByRole('button', { name: action, exact: true })).toBeEnabled()
    }
  })
})
