import { expect } from 'e2e'
import { test } from '../../engines/web'

test.describe('H5 B4 Marketing Blocks', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/?demo=marketing-blocks')
    await expect(browser.locator('[data-marketing-demo="state"]')).toHaveText('host=0;plan=none;period=month;receipts=0;steps=0')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('hero grants open a real local guide and reject unavailable actions', async ({ browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    await expect(demo.getByRole('button', { name: 'Purchase service', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Explore the local guide', exact: true }).click()
    await expect(demo.getByRole('region', { name: 'Local guide', exact: true })).toContainText('bind application-owned data and typed events')
    await expect(browser.locator('[data-marketing-demo="state"]')).toContainText('host=1;')
    await demo.getByRole('button', { name: 'Disabled', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Explore the local guide', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Close guide', exact: true }).click()
    await expect(demo.getByRole('region', { name: 'Local guide', exact: true })).toHaveCount(0)
    await expect(browser.locator('[data-marketing-demo="state"]')).toContainText('host=1;')
  })

  test('articles paginate without truncation and open eligible current details', async ({ browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    await expect(browser.locator('[data-article]')).toHaveCount(3)
    await expect(demo.getByRole('button', { name: 'Previous articles', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Read Unpublished field notes', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Read A source-first workflow', exact: true }).click()
    await expect(browser.locator('[data-marketing-demo="article"]')).toContainText('Your application supplies records and handles emitted intents.')
    await demo.getByRole('button', { name: 'Close article', exact: true }).click()
    await demo.getByRole('button', { name: 'Next articles', exact: true }).click()
    await expect(browser.locator('[data-article]')).toHaveCount(1)
    await expect(demo.getByRole('button', { name: 'Next articles', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Read Design beyond the happy path', exact: true }).click()
    await expect(browser.locator('[data-marketing-demo="article"]')).toContainText('must not claim external delivery')
    await demo.getByRole('button', { name: 'Loading', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Read Design beyond the happy path', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Close article', exact: true }).click()
    await expect(browser.locator('[data-marketing-demo="article"]')).toHaveCount(0)
  })

  test('plan selection waits for host acceptance and preserves rejection evidence', async ({ browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    const state = browser.locator('[data-marketing-demo="state"]')
    await expect(demo.getByRole('button', { name: 'Choose Unavailable example', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Legacy period', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Yearly', exact: true }).click()
    await expect(browser.locator('[data-plan="team"]')).toContainText('$240 / year')
    await expect(browser.locator('[data-plan="team"]')).toContainText('Review responsibility')
    await demo.getByRole('button', { name: 'Choose Team example', exact: true }).click()
    await expect(state).toContainText('plan=none;period=year;')
    await expect(demo.getByRole('button', { name: 'Monthly', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Choose Self-guided example', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Reject local plan choice', exact: true }).click()
    await expect(demo).toContainText('Local plan choice rejected. No charge was made.')
    await expect(state).toContainText('plan=none;')
    await demo.getByRole('button', { name: 'Clear plan error', exact: true }).click()
    await demo.getByRole('button', { name: 'Choose Team example', exact: true }).click()
    await demo.getByRole('button', { name: 'Accept local plan choice', exact: true }).click()
    await expect(state).toContainText('plan=team;period=year;')
    await expect(browser.locator('[data-plan="team"]')).toContainText('Selected')
    await expect(demo.getByRole('button', { name: 'Choose Team example', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Monthly', exact: true }).click()
    await expect(state).toContainText('plan=none;period=month;')
  })

  test('FAQ supports keyboard disclosure stable IDs and long answers', async ({ app, browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    const question = demo.getByRole('button', { name: 'Who owns the application decisions?', exact: true })
    await expect(question).toHaveAttribute('aria-expanded', 'false')
    await expect(demo.getByRole('button', { name: 'Restricted question', exact: true })).toBeDisabled()
    await question.focus()
    await browser.keyboard.press('Enter')
    await expect(question).toHaveAttribute('aria-expanded', 'true')
    await expect(question).toHaveAttribute('aria-controls', 'marketing-demo-answer-ownership')
    await expect(browser.locator('#marketing-demo-answer-ownership')).toContainText('Your application owns data, permissions, navigation and persistence.')
    await demo.getByRole('button', { name: 'Long content', exact: true }).click()
    await expect(browser.locator('#marketing-demo-answer-ownership')).toContainText('requiring a hover gesture.')
    await app.screenshot('h5-marketing-long-mobile')
    await browser.setViewport({ width: 1280, height: 900 })
    await app.screenshot('h5-marketing-long-wide')
    await question.focus()
    await browser.keyboard.press('Space')
    await expect(question).toHaveAttribute('aria-expanded', 'false')
    await expect(browser.locator('#marketing-demo-answer-ownership')).toHaveCount(0)
  })

  test('contact validates actual input and saves only explicitly accepted local receipts', async ({ browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    const state = browser.locator('[data-marketing-demo="state"]')
    const submit = demo.getByRole('button', { name: 'Submit contact request', exact: true })
    await submit.click()
    await expect(demo).toContainText('Enter your name.')
    await expect(demo).toContainText('Enter a valid email address.')
    await expect(demo).toContainText('Write at least 10 characters.')
    await demo.getByRole('textbox', { name: 'Name', exact: true }).fill('Varo Reader')
    await demo.getByRole('textbox', { name: 'Email', exact: true }).fill('invalid-address')
    await demo.getByRole('textbox', { name: 'Message', exact: true }).fill('Please explain native source ownership.')
    await submit.click()
    await expect(demo).toContainText('Enter a valid email address.')
    await expect(state).toContainText('receipts=0;')
    await demo.getByRole('textbox', { name: 'Email', exact: true }).fill('reader@example.com')
    await submit.click()
    await expect(demo.getByRole('textbox', { name: 'Name', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: 'Awaiting acknowledgement…', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Reject local contact receipt', exact: true }).click()
    await expect(demo).toContainText('Local request rejected. Your draft is preserved; no email was sent.')
    await expect(demo.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('Please explain native source ownership.')
    await submit.click()
    await demo.getByRole('button', { name: 'Cancel request', exact: true }).click()
    await expect(state).toContainText('receipts=0;')
    await submit.click()
    await demo.getByRole('button', { name: 'Accept local contact receipt', exact: true }).click()
    await expect(state).toContainText('receipts=1;')
    await expect(demo).toContainText('Local receipt 1 saved for Varo Reader. No email was sent;')
    await expect(browser.locator('[data-marketing-demo="receipts"]')).toContainText('Please explain native source ownership.')
  })

  test('process actions advance only the local instruction exploration', async ({ browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    await expect(demo.getByRole('button', { name: 'Open contact instructions', exact: true })).toBeDisabled()
    await expect(browser.locator('[data-process-step="inspect"]')).toHaveAttribute('data-state', 'active')
    await demo.getByRole('button', { name: 'Open workflow instructions', exact: true }).click()
    await expect(demo.getByRole('region', { name: 'Local guide', exact: true })).toContainText('does not install or publish anything')
    await expect(browser.locator('[data-process-step="inspect"]')).toHaveAttribute('data-state', 'completed')
    await expect(demo.getByRole('button', { name: 'Open workflow instructions', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Open contact instructions', exact: true }).click()
    await expect(demo.getByRole('region', { name: 'Local guide', exact: true })).toContainText('there is no email transport')
    await expect(browser.locator('[data-process-step="contact"]')).toHaveAttribute('data-state', 'completed')
    await expect(browser.locator('[data-marketing-demo="state"]')).toContainText('steps=2')
  })

  test('loading empty error and disabled states retain content and recover through real controls', async ({ browser }) => {
    const demo = browser.locator('#marketing-blocks-demo')
    for (const mode of ['Loading', 'Error', 'Disabled']) {
      await demo.getByRole('button', { name: mode, exact: true }).click()
      for (const name of ['Explore the local guide', 'Read A source-first workflow', 'Choose Team example', 'Who owns the application decisions?', 'Submit contact request', 'Open workflow instructions']) {
        await expect(demo.getByRole('button', { name, exact: true })).toBeDisabled()
      }
      await expect(demo).toContainText('Build the interface. Keep the source.')
      await expect(browser.locator('[data-marketing-demo="state"]')).toHaveText('host=0;plan=none;period=month;receipts=0;steps=0')
    }
    await demo.getByRole('button', { name: 'Empty', exact: true }).click()
    for (const text of ['No introduction available.', 'No articles available.', 'No plans available.', 'No questions available.', 'No process steps available.']) {
      await expect(demo).toContainText(text)
    }
    await expect(demo.getByRole('button', { name: 'Submit contact request', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: 'Ready', exact: true }).click()
    await expect(demo.getByRole('button', { name: 'Explore the local guide', exact: true })).toBeEnabled()
    await expect(browser.locator('[data-article]')).toHaveCount(3)
  })
})
