import { setTimeout as delay } from 'node:timers/promises'
import { expect } from 'e2e'
import { test } from '../../engines/web'

const lengthModel = '本地逐词长度（Unicode 字符计数，不是 token 数）'

test.describe('H5 B3 Model Compare', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/?demo=model-compare')
    await expect(browser.locator('[data-compare-demo="selection"]')).toHaveText('left=uppercase;right=reverse')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('controlled selections reject unavailable disabled duplicate and no-op choices', async ({ browser, screen, app }) => {
    const left = browser.locator('[data-compare-side="left"]')
    await left.getByRole('combobox').click()
    for (const name of ['本地大写转换', '本地逐词反转', '未连接的模型服务 — 没有服务连接', '应用禁用的转换 — 应用禁止选择']) {
      await expect(screen.getByRole('option', { name, exact: true })).toBeDisabled()
    }
    await screen.getByRole('option', { name: lengthModel, exact: true }).click()
    await expect(left.getByRole('combobox')).toContainText(lengthModel)
    await expect(browser.locator('[data-compare-demo="selection"]')).toHaveText('left=length;right=reverse')
    await expect(left).toContainText('尚无比较结果')
    await app.screenshot('h5-model-compare-controlled-selection')
  })

  test('catalog loading error empty and revoked availability block new work', async ({ browser, screen }) => {
    const left = browser.locator('[data-compare-side="left"]')
    const input = screen.getByRole('textbox', { name: '共享提示词' })
    await screen.getByRole('button', { name: '目录加载态', exact: true }).click()
    await expect(left).toContainText('正在加载模型目录')
    await expect(input).toBeDisabled()
    await screen.getByRole('button', { name: '目录错误态', exact: true }).click()
    await expect(left.getByRole('alert')).toContainText('目录加载错误')
    await screen.getByRole('button', { name: '空目录', exact: true }).click()
    await expect(left).toContainText('暂无可选模型')
    await expect(input).toBeDisabled()
    await screen.getByRole('button', { name: '恢复目录', exact: true }).click()
    await screen.getByRole('button', { name: '切换左侧可用性', exact: true }).click()
    await expect(left).toContainText('当前模型不可用')
    await expect(input).toBeDisabled()
    await screen.getByRole('button', { name: '切换左侧可用性', exact: true }).click()
    await expect(input).toBeEnabled()
  })

  test('shared prompt honors controlled rejection reset and absent local ownership', async ({ browser, screen }) => {
    const input = screen.getByRole('textbox', { name: '共享提示词' })
    await screen.getByRole('button', { name: '外部清空提示词', exact: true }).click()
    await expect(input).toHaveValue('')
    await screen.getByRole('button', { name: '拒绝提示词更新', exact: true }).click()
    await input.fill('unaccepted draft')
    await expect(input).toHaveValue('')
    await expect(screen.getByRole('button', { name: '发送', exact: true })).toBeDisabled()
    await screen.getByRole('button', { name: '接受提示词更新', exact: true }).click()
    await input.fill('  accepted draft  ')
    await expect(input).toHaveValue('  accepted draft  ')
    await screen.getByRole('button', { name: '拒绝提示词更新', exact: true }).click()
    await input.fill('unaccepted replacement')
    await expect(input).toHaveValue('  accepted draft  ')
    await screen.getByRole('button', { name: '接受提示词更新', exact: true }).click()
    await screen.getByRole('button', { name: '外部清空提示词', exact: true }).click()
    await expect(input).toHaveValue('')
    await screen.getByRole('button', { name: '使用非受控输入', exact: true }).click()
    await input.fill('  alpha bravo  ')
    await screen.getByRole('button', { name: '发送', exact: true }).click()
    await expect(input).toHaveValue('  alpha bravo  ')
    await expect(browser.locator('[data-compare-output="right"]')).toContainText('ahpla ovarb')
    await expect(browser.locator('[data-compare-side="right"]')).toContainText('已完成')
  })

  test('one-side failure allows independent retry continuation and honest supplied metrics', async ({ browser, screen, app }) => {
    const left = browser.locator('[data-compare-side="left"]')
    const right = browser.locator('[data-compare-side="right"]')
    const leftOutput = browser.locator('[data-compare-output="left"]')
    const rightOutput = browser.locator('[data-compare-output="right"]')
    await expect(left).toContainText('耗时：未提供')
    await expect(left).toContainText('费用：未提供')
    await screen.getByRole('button', { name: '发送', exact: true }).click()
    await expect(left.getByRole('alert')).toContainText('首次执行失败')
    await expect(rightOutput).toContainText('ahpla')
    await expect(left.getByRole('combobox')).toBeDisabled()
    await expect(right.getByRole('combobox')).toBeDisabled()
    await expect(screen.getByRole('textbox', { name: '共享提示词' })).toBeDisabled()
    await screen.getByRole('button', { name: '重试左侧', exact: true }).click()
    await expect(leftOutput).toContainText('ALPHA BRAVO')
    await expect(rightOutput).toContainText('ahpla ovarb eilrahc')
    await expect(left).toContainText('已完成', { timeout: 15_000 })
    await expect(right).toContainText('已完成', { timeout: 15_000 })
    await expect(leftOutput).toContainText('SIERRA TANGO')
    await expect(rightOutput).toContainText('arreis ognat')
    await expect(browser.locator('[data-compare-demo="right-lifecycle"]')).toContainText('cleanups=1;active=false;timers=0')
    await screen.getByRole('button', { name: '显示本地实测耗时', exact: true }).click()
    await expect(left).toContainText('应用测量耗时：')
    await expect(right).toContainText('费用：未提供')
    const preserved = await rightOutput.textContent()
    await left.getByRole('combobox').click()
    await screen.getByRole('option', { name: lengthModel, exact: true }).click()
    await expect(leftOutput).toHaveText('')
    expect(await rightOutput.textContent()).toBe(preserved)
    await app.screenshot('h5-model-compare-independent-results')
    await browser.setViewport({ width: 1024, height: 900 })
    await app.screenshot('h5-model-compare-wide-results')
  })

  test('disabled input preserves side-specific stop while the other producer continues', async ({ browser, screen, app }) => {
    await screen.getByRole('textbox', { name: '共享提示词' }).fill('alpha bravo charlie delta echo foxtrot golf hotel india juliet '.repeat(4))
    await screen.getByRole('button', { name: '发送', exact: true }).click()
    await expect(screen.getByRole('button', { name: '重试左侧', exact: true })).toBeEnabled()
    await screen.getByRole('button', { name: '重试左侧', exact: true }).click()
    await expect(browser.locator('[data-compare-output="left"]')).toContainText('ALPHA')
    await screen.getByRole('button', { name: '禁用输入', exact: true }).click()
    await expect(screen.getByRole('textbox', { name: '共享提示词' })).toBeDisabled()
    await screen.getByRole('button', { name: '停止左侧', exact: true }).click()
    await expect(browser.locator('[data-compare-side="left"]')).toContainText('已停止')
    const receipt = browser.locator('[data-compare-demo="left-lifecycle"]')
    await expect(receipt).toContainText('cleanups=2;active=false;timers=0')
    const stopped = await receipt.textContent()
    await expect(browser.locator('[data-compare-output="right"]')).toContainText('ahpla ovarb eilrahc atled')
    await delay(900)
    expect(await receipt.textContent()).toBe(stopped)
    await expect(screen.getByRole('button', { name: '停止右侧', exact: true })).toBeEnabled()
    await screen.getByRole('button', { name: '停止右侧', exact: true }).click()
    await expect(browser.locator('[data-compare-demo="right-lifecycle"]')).toContainText('cleanups=1;active=false;timers=0')
    await app.screenshot('h5-model-compare-independent-stop')
  })

  test('closing active comparison releases both iterators and pending timers', async ({ browser, screen }) => {
    await screen.getByRole('button', { name: '发送', exact: true }).click()
    await expect(screen.getByRole('button', { name: '重试左侧', exact: true })).toBeEnabled()
    await screen.getByRole('button', { name: '重试左侧', exact: true }).click()
    await expect(browser.locator('[data-compare-output="left"]')).toContainText('ALPHA')
    await screen.getByRole('button', { name: '关闭并清理比较', exact: true }).click()
    const left = browser.locator('[data-compare-demo="left-lifecycle"]')
    const right = browser.locator('[data-compare-demo="right-lifecycle"]')
    await expect(left).toContainText('cleanups=2;active=false;timers=0')
    await expect(right).toContainText('cleanups=1;active=false;timers=0')
    await expect(browser.locator('[data-compare-side]')).toHaveCount(0)
    const stopped = [await left.textContent(), await right.textContent()]
    await delay(900)
    expect([await left.textContent(), await right.textContent()]).toEqual(stopped)
  })

  test('standalone selector composes with ordinary Chat without a comparison stream', async ({ browser, screen, app }) => {
    await screen.getByRole('button', { name: '显示普通 Chat 组合', exact: true }).click()
    const chat = browser.locator('[data-compare-demo="ordinary-chat"]')
    await chat.getByRole('combobox').click()
    await screen.getByRole('option', { name: lengthModel, exact: true }).click()
    await chat.getByRole('textbox').fill('boat')
    await chat.getByRole('button', { name: '发送', exact: true }).click()
    await expect(browser.locator('[data-compare-demo="ordinary-chat"] .agent-stream')).toContainText('boat(4)')
    await expect(browser.locator('[data-compare-demo="left-lifecycle"]')).toContainText('cleanups=1;active=false;timers=0')
    await expect(browser.locator('[data-compare-demo="right-lifecycle"]')).toContainText('steps=0;cleanups=0;active=false;timers=0')
    await chat.getByRole('button', { name: '新建会话', exact: true }).click()
    await expect(chat.getByRole('textbox')).toHaveValue('')
    await expect(chat).toContainText('有什么可以帮你？')
    await app.screenshot('h5-model-selector-ordinary-chat')
  })
})
