import { expect } from 'e2e'
import { test } from '../../engines/web'

test.describe('H5 B2 Source Chat', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/?demo=source-chat')
    await expect(browser.locator('[data-source-demo="state"]')).toContainText('response=idle;')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('source availability and connection require explicit scope selection', async ({ browser }) => {
    const demo = browser.locator('#source-chat-demo')
    const state = browser.locator('[data-source-demo="state"]')
    const input = demo.getByRole('textbox')
    await expect(demo).toContainText('本地确定性演示')
    await expect(demo.getByRole('button', { name: '创建工单', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: '停用本地知识库', exact: true }).click()
    await expect(state).toContainText('scope=none;')
    await expect(input).toBeDisabled()
    await expect(demo).toContainText('请先连接并启用至少一个可用来源')
    await demo.getByRole('button', { name: '启用本地知识库', exact: true }).click()
    await expect(input).toBeEnabled()
    await demo.getByRole('button', { name: '模拟来源不可用', exact: true }).click()
    await expect(state).toContainText('scope=none;')
    await expect(demo.getByRole('button', { name: '连接本地知识库', exact: true })).toBeEnabled()
    await expect(input).toBeDisabled()
    await demo.getByRole('button', { name: '恢复演示来源', exact: true }).click()
    await expect(state).toContainText('scope=none;')
    await demo.getByRole('button', { name: '启用本地知识库', exact: true }).click()
    await demo.getByRole('button', { name: '连接演示归档', exact: true }).click()
    await expect(state).toContainText('connections=1;')
    await expect(demo.getByRole('button', { name: '连接演示归档', exact: true })).toHaveCount(0)
    await expect(demo).toContainText('连接中')
    await demo.getByRole('button', { name: '完成演示连接', exact: true }).click()
    await expect(state).toContainText('scope=handbook;')
    await expect(demo.getByRole('button', { name: '完成演示连接', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: '禁用操作', exact: true }).click()
    await expect(demo.getByRole('button', { name: '启用演示归档', exact: true })).toBeDisabled()
    await expect(input).toBeDisabled()
    await expect(state).toContainText('toggles=3;')
    await expect(state).toContainText('submits=0;')
    await demo.getByRole('button', { name: '启用操作', exact: true }).click()
    await demo.getByRole('button', { name: '启用演示归档', exact: true }).click()
    await expect(state).toContainText('scope=handbook,archive;')
    await expect(state).toContainText('toggles=4;')
  })

  test('retrieval progress settles into visible receipts and application-opened citations', async ({ app, browser }) => {
    const demo = browser.locator('#source-chat-demo')
    const state = browser.locator('[data-source-demo="state"]')
    const input = demo.getByRole('textbox')
    await input.fill('如何申请退货？')
    await demo.getByRole('button', { name: '发送', exact: true }).click()
    await expect(state).toContainText('response=retrieving;')
    await expect(input).toHaveValue('')
    await expect(browser.locator('.agent-retrieval [data-status="queued"]')).toContainText('本地知识库')
    await expect(demo.getByRole('button', { name: '停用本地知识库', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '连接演示归档', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '创建工单', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: '演示读取', exact: true }).click()
    await expect(browser.locator('.agent-retrieval [data-status="reading"]')).toContainText('正在读取本地演示条目')
    await expect(demo.getByRole('button', { name: '演示读取', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: '演示成功', exact: true }).click()
    await expect(state).toContainText('response=answered;')
    await expect(browser.locator('[data-source-response="answered"]')).toContainText('已提供有来源的回答')
    await expect(browser.locator('.agent-source-receipt [data-status="read"]')).toContainText('1 项')
    await demo.getByRole('button', { name: '查看本地知识库回执', exact: true }).click()
    await expect(state).toContainText('receipts=1;')
    await expect(browser.locator('[data-source-demo="document"]')).toContainText('实际政策由商家确认')
    await browser.locator('.agent-citations__item').click()
    await expect(state).toContainText('citations=1;')
    await expect(browser.locator('[data-source-demo="document"]')).toContainText('本地演示原文：签收后七天内可申请退货')
    await demo.getByRole('button', { name: '禁用操作', exact: true }).click()
    await expect(browser.locator('.agent-source-receipt')).toContainText('本地知识库回执')
    await expect(browser.locator('.agent-citations__item')).toBeVisible()
    await expect(browser.locator('.agent-citations__item')).toBeDisabled()
    await expect(demo.getByRole('button', { name: '查看本地知识库回执', exact: true })).toBeDisabled()
    await expect(state).toContainText('citations=1;receipts=1;tickets=0')
    await app.screenshot('h5-source-chat-disabled-evidence')
  })

  test('failure retry, empty and out-of-scope results emit one ticket intent per application grant', async ({ browser }) => {
    const demo = browser.locator('#source-chat-demo')
    const state = browser.locator('[data-source-demo="state"]')
    const request = browser.locator('[data-source-demo="ticket"]')
    await demo.getByRole('textbox').fill('没有找到退货资料')
    await demo.getByRole('button', { name: '发送', exact: true }).click()
    await demo.getByRole('button', { name: '演示失败', exact: true }).click()
    await expect(demo.getByRole('alert')).toContainText('检索失败，尚未生成回答')
    await expect(browser.locator('.agent-source-receipt [data-status="failed"]')).toContainText('演示读取失败')
    await expect(browser.locator('.agent-citations__item')).toHaveCount(0)
    await demo.getByRole('button', { name: '禁用操作', exact: true }).click()
    await expect(demo.getByRole('button', { name: '重试本地知识库', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '连接本地知识库回执', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '创建工单', exact: true })).toBeDisabled()
    await expect(state).toContainText('tickets=0')
    await demo.getByRole('button', { name: '启用操作', exact: true }).click()
    await demo.getByRole('button', { name: '连接本地知识库回执', exact: true }).click()
    await expect(state).toContainText('connections=1;')
    await expect(demo.getByRole('alert')).toContainText('演示没有执行连接')
    await demo.getByRole('button', { name: '创建工单', exact: true }).click()
    await expect(request).toContainText('转交申请（未创建工单）：没有找到退货资料；原因=failed；来源=handbook')
    await expect(demo.getByRole('button', { name: '创建工单', exact: true })).toBeDisabled()
    await demo.getByRole('button', { name: '停用本地知识库', exact: true }).click()
    await expect(demo.getByRole('button', { name: '重试本地知识库', exact: true })).toHaveCount(0)
    await expect(browser.locator('.agent-retrieval [data-status="failed"]')).toBeVisible()
    await expect(state).toContainText('submits=1;')
    await demo.getByRole('button', { name: '启用本地知识库', exact: true }).click()
    await demo.getByRole('button', { name: '重试本地知识库', exact: true }).click()
    await expect(state).toContainText('response=retrieving;')
    await expect(state).toContainText('submits=2;')
    await demo.getByRole('button', { name: '演示空结果', exact: true }).click()
    await expect(browser.locator('[data-source-response="empty"]')).toContainText('没有找到相关内容')
    await expect(browser.locator('.agent-source-receipt [data-status="read"]')).toContainText('0 项')
    await demo.getByRole('button', { name: '创建工单', exact: true }).click()
    await expect(request).toContainText('原因=empty；来源=handbook')
    await expect(state).toContainText('tickets=2')
    await demo.getByRole('textbox').fill('查询财务系统')
    await demo.getByRole('button', { name: '发送', exact: true }).click()
    await demo.getByRole('button', { name: '演示超出范围', exact: true }).click()
    await expect(browser.locator('[data-source-response="out-of-scope"]')).toContainText('问题超出当前知识范围')
    await expect(browser.locator('.agent-source-receipt [data-status="skipped"]')).toBeVisible()
    await expect(browser.locator('.agent-citations__item')).toHaveCount(0)
    await demo.getByRole('button', { name: '创建工单', exact: true }).click()
    await expect(request).toContainText('查询财务系统；原因=out-of-scope；来源=handbook')
    await expect(state).toContainText('tickets=3')
    await expect(demo.getByRole('button', { name: '创建工单', exact: true })).toBeDisabled()
  })

  test('unbound prompt survives submit and disabled stop remains a cancellation escape', async ({ browser }) => {
    const demo = browser.locator('#source-chat-demo')
    const state = browser.locator('[data-source-demo="state"]')
    await demo.getByRole('button', { name: '切换为非受控输入', exact: true }).click()
    await expect(state).toContainText('mode=uncontrolled;')
    await demo.getByRole('textbox').fill('组件保留的本地草稿')
    await demo.getByRole('button', { name: '发送', exact: true }).click()
    await expect(state).toContainText('response=retrieving;')
    await expect(browser.locator('[data-source-demo="question"]')).toContainText('组件保留的本地草稿')
    await demo.getByRole('button', { name: '禁用操作', exact: true }).click()
    await expect(demo.getByRole('textbox')).toBeDisabled()
    await demo.getByRole('button', { name: '停止生成', exact: true }).click()
    await expect(state).toContainText('response=idle;')
    await expect(browser.locator('.agent-retrieval [data-status="skipped"]')).toContainText('应用已停止本地演示检索')
    await expect(demo.getByRole('button', { name: '停止生成', exact: true })).toHaveCount(0)
    await expect(demo.getByRole('textbox')).toHaveValue('组件保留的本地草稿')
    await demo.getByRole('button', { name: '启用操作', exact: true }).click()
    await demo.getByRole('button', { name: '切换为受控输入', exact: true }).click()
    await expect(state).toContainText('mode=controlled;')
    await expect(demo.getByRole('textbox')).toHaveValue('')
    await expect(demo.getByRole('button', { name: '发送', exact: true })).toBeDisabled()
  })
})
