import { setTimeout as delay } from 'node:timers/promises'
import { expect } from 'e2e'
import { test } from '../../engines/web'

test.describe('H5 B2 Workspace', { platforms: ['h5'] }, () => {
  test.beforeEach(async ({ app, browser }) => {
    await browser.setViewport({ width: 375, height: 812 })
    await app.open('/?demo=workspace')
    await expect(browser.locator('[data-workspace-demo="state"]')).toContainText('action=ready')
  })
  test.afterEach(async ({ webRuntime }) => {
    const diagnostics = await webRuntime.diagnostics()
    expect(diagnostics.pageErrors).toEqual([])
    expect(diagnostics.console.filter(message => message.type === 'error')).toEqual([])
  })

  test('branch select pin and disabled controls preserve application-owned versions', async ({ app, browser }) => {
    const demo = browser.locator('#workspace-demo')
    const state = browser.locator('[data-workspace-demo="state"]')
    await expect(demo.getByRole('button', { name: '选择初始方案', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: '禁用工作区操作', exact: true }).click()
    await expect(demo.getByRole('button', { name: '从初始方案创建分支', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '选择备选方案', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '固定初始方案', exact: true })).toBeDisabled()
    await expect(demo.getByRole('button', { name: '批准本地词数工具', exact: true })).toBeDisabled()
    await expect(state).toContainText('intents=0;action=ready')
    await demo.getByRole('button', { name: '启用工作区操作', exact: true }).click()
    await demo.getByRole('button', { name: '从初始方案创建分支', exact: true }).click()
    await expect(state).toContainText('version=branch-1;versions=3;')
    await expect(demo).toContainText('来源：初始方案')
    await demo.getByRole('button', { name: '固定分支 1', exact: true }).click()
    await expect(state).toContainText('pinned=branch-1;')
    await expect(demo.getByRole('button', { name: '固定分支 1', exact: true })).toHaveCount(0)
    await demo.getByRole('button', { name: '选择备选方案', exact: true }).focus()
    await browser.keyboard.press('Enter')
    await expect(state).toContainText('version=alternative;')
    await expect(demo.getByRole('button', { name: '选择备选方案', exact: true })).toHaveCount(0)
    // A removed selection control must not become a different focused action.
    await browser.keyboard.press('Enter')
    await expect(browser.locator('#workspace-demo [role="log"]')).toContainText('本地草稿：保留人工审批，再运行工具。')
    await expect(state).toContainText('intents=3;action=select:alternative')
    await app.screenshot('h5-workspace-versions')
  })

  test('approval decisions and retry compute a local result without optimistic completion', async ({ app, browser }) => {
    const demo = browser.locator('#workspace-demo')
    const state = browser.locator('[data-workspace-demo="state"]')
    await demo.getByRole('button', { name: '批准本地词数工具', exact: true }).click()
    await expect(state).toContainText('status=waiting;processed=0;words=0;')
    await expect(state).toContainText('action=approval-requested')
    await demo.getByRole('button', { name: '拒绝本地执行', exact: true }).click()
    await expect(state).toContainText('action=approval-declined')
    await demo.getByRole('button', { name: '批准本地词数工具', exact: true }).click()
    await demo.getByRole('button', { name: '批准本地执行', exact: true }).click()
    await expect(state).toContainText('status=running;')
    await expect(demo.getByRole('button', { name: '从初始方案创建分支', exact: true })).toBeDisabled()
    await expect(state).toContainText('status=failed;')
    await expect(demo).toContainText('本地演示错误：第二条输入被故意拒绝。')
    await demo.getByRole('button', { name: '重试本地词数工具', exact: true }).click()
    await expect(state).toContainText('status=running;')
    await expect(state).toContainText('status=completed;processed=8;words=24;')
    await expect(demo).toContainText('本地已处理 8/8 条，累计 24 个词。')
    await expect(demo.getByRole('button', { name: '重试本地词数工具', exact: true })).toHaveCount(0)
    await expect(demo.getByRole('button', { name: '取消当前任务', exact: true })).toHaveCount(0)
    await app.screenshot('h5-workspace-local-result')
  })

  test('busy cancel stops local work and requires a new approval', async ({ app, browser }) => {
    const demo = browser.locator('#workspace-demo')
    const state = browser.locator('[data-workspace-demo="state"]')
    await demo.getByRole('button', { name: '批准本地词数工具', exact: true }).click()
    await demo.getByRole('button', { name: '批准本地执行', exact: true }).click()
    await expect(state).toContainText('status=failed;')
    await demo.getByRole('button', { name: '重试本地词数工具', exact: true }).click()
    await expect(state).toContainText('status=running;')
    await demo.getByRole('button', { name: '取消当前任务', exact: true }).click()
    await expect(state).toContainText('status=waiting;')
    await expect(state).toContainText('action=cancelled')
    const stopped = await state.textContent()
    // Beyond two local producer intervals: cancellation must prevent later computation.
    await delay(1000)
    expect(await state.textContent()).toBe(stopped)
    await expect(demo.getByRole('button', { name: '取消当前任务', exact: true })).toHaveCount(0)
    await expect(demo.getByRole('button', { name: '批准本地词数工具', exact: true })).toBeEnabled()
    await app.screenshot('h5-workspace-cancelled')
  })
})
