packages:
  - .
  - ../../packages/theme

overrides:
  vue: 3.5.42
  undici: 7.29.0

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@weapp-core/api@0.3.1'
  - '@weapp-core/init@6.0.18'
  - '@weapp-core/schematics@6.2.2'
  - '@weapp-vite/ast@7.1.0'
  - '@weapp-vite/devtools-runtime@0.4.17'
  - '@weapp-vite/eslint@0.2.3'
  - '@weapp-vite/mcp@1.5.2'
  - '@weapp-vite/miniprogram-automator@1.2.17'
  - '@weapp-vite/qr@1.1.2'
  - '@weapp-vite/volar@2.1.6'
  - '@weapp-vite/web@1.5.0'
  - '@wevu/api@0.3.1'
  - '@wevu/compiler@7.1.0'
  - '@wevu/web-apis@1.2.41'
  - rolldown-require@2.0.28
  - weapp-ide-cli@6.1.3
  - weapp-tailwindcss@5.5.3
  - weapp-vite@7.1.0
  - wevu@7.1.0
  - '@weapp-tailwindcss/postcss@3.3.2'
