packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@weapp-core/api@0.2.0'
  - '@weapp-core/init@6.0.16'
  - '@weapp-core/schematics@6.2.1'
  - '@weapp-vite/ast@6.24.0'
  - '@weapp-vite/devtools-runtime@0.4.17'
  - '@weapp-vite/eslint@0.2.2'
  - '@weapp-vite/mcp@1.5.0'
  - '@weapp-vite/miniprogram-automator@1.2.16'
  - '@weapp-vite/qr@1.1.2'
  - '@weapp-vite/volar@2.1.5'
  - '@weapp-vite/web@1.4.14'
  - '@wevu/api@0.2.18'
  - '@wevu/compiler@6.24.0'
  - '@wevu/web-apis@1.2.37'
  - rolldown-require@2.0.27
  - weapp-ide-cli@6.1.0
  - weapp-vite@6.24.0
  - wevu@6.24.0
