import { readdir, readFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createThemeCssVariables, renderThemeCssVariables } from '../packages/theme/src/css.ts'
import { createTheme } from '../packages/theme/src/theme.ts'
import { projectFiles } from './registry-artifacts.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)
if (args.some(arg => arg !== '--check')) {
  throw new Error('Usage: node scripts/sync-styles.mjs [--check]')
}
const check = args.includes('--check')

// Explicit aggregate order. Each component keeps its original rule order, including
// its font reset and reduced-motion overrides. Identical renderer CSS has one source.
const components = [
  ['button', 'h5.css', 'weapp-vite.css'],
  ['input', 'h5.css', 'weapp-vite.css'],
  ['checkbox', 'h5.css', 'weapp-vite.css'],
  ['radio', 'h5.css', 'weapp-vite.css'],
  ['input-number', 'h5.css', 'weapp-vite.css'],
  ['select', 'h5.css', 'weapp-vite.css'],
  ['switch', 'h5.css', 'weapp-vite.css'],
  ['loading', 'style.css', 'style.css'],
  ['toast', 'h5.css', 'weapp-vite.css'],
  ['rate', 'h5.css', 'weapp-vite.css'],
  ['range', 'style.css', 'style.css'],
  ['searchbar', 'h5.css', 'weapp-vite.css'],
  ['form', 'h5.css', 'weapp-vite.css'],
  ['date-field', 'h5.css', 'weapp-vite.css'],
  ['calendar', 'h5.css', 'weapp-vite.css'],
  ['date-picker', 'h5.css', 'weapp-vite.css'],
  ['picker', 'h5.css', 'weapp-vite.css'],
  ['cascader', 'h5.css', 'weapp-vite.css'],
  ['number-keyboard', 'h5.css', 'weapp-vite.css'],
  ['short-password', 'style.css', 'style.css'],
  ['uploader', 'h5.css', 'weapp-vite.css'],
  ['indicator', 'h5.css', 'weapp-vite.css'],
  ['elevator', 'h5.css', 'weapp-vite.css'],
  ['menu', 'h5.css', 'weapp-vite.css'],
  ['pagination', 'h5.css', 'weapp-vite.css'],
  ['tabs', 'h5.css', 'weapp-vite.css'],
  ['icon', 'style.css', 'style.css'],
  ['card', 'h5.css', 'weapp-vite.css'],
  ['avatar', 'style.css', 'style.css'],
  ['badge', 'style.css', 'style.css'],
  ['tag', 'h5.css', 'weapp-vite.css'],
  ['empty', 'style.css', 'style.css'],
  ['skeleton', 'h5.css', 'weapp-vite.css'],
  ['progress', 'style.css', 'style.css'],
  ['steps', 'h5.css', 'weapp-vite.css'],
  ['notice-bar', 'h5.css', 'weapp-vite.css'],
  ['safe-area', 'style.css', 'style.css'],
  ['collapse', 'h5.css', 'weapp-vite.css'],
  ['popover', 'h5.css', 'weapp-vite.css'],
  ['action-sheet', 'h5.css', 'weapp-vite.css'],
  ['swipe-cell', 'style.css', 'style.css'],
  ['signature', 'h5.css', 'weapp-vite.css'],
  ['watermark', 'style.css', 'style.css'],
  ['pull-refresh', 'h5.css', 'weapp-vite.css'],
  ['list', 'h5.css', 'weapp-vite.css'],
  ['image', 'h5.css', 'weapp-vite.css'],
  ['divider', 'style.css', 'style.css'],
  ['grid', 'style.css', 'style.css'],
  ['layout', 'style.css', 'style.css'],
  ['space', 'style.css', 'style.css'],
  ['sticky', 'style.css', 'style.css'],
  ['region-picker', 'h5.css', 'weapp-vite.css'],
  ['breadcrumb', 'h5.css', 'weapp-vite.css'],
  ['map', 'style.css', 'style.css'],
  ['navbar', null, 'weapp-vite.css'],
  ['popup', null, 'weapp-vite.css'],
  ['tabbar', null, 'weapp-vite.css'],
  ['robot-chat', null, 'weapp-vite.css'],
  ['dialog', null, 'weapp-vite.css'],
  ['input-otp', 'h5.css', 'weapp-vite.css'],
  ['drawer', 'h5.css', 'weapp-vite.css'],
]

const header = '/* Generated by scripts/sync-styles.mjs. Edit the canonical Registry sources, not this file. */\n'
const read = path => readFile(resolve(root, path), 'utf8')

// Keep the aggregate list and the installer mappings in agreement. Otherwise a new
// component can look correct in source installs but silently disappear from npm CSS.
const sourcePaths = new Set()
for (const [name, h5, weapp] of components) {
  const manifest = JSON.parse(await read(`registry/components/${name}/registry.json`))
  for (const [target, filename] of [['h5', h5], ['weapp', weapp]]) {
    const source = filename && `registry/themes/components/${name}/${filename}`
    if (source) { sourcePaths.add(resolve(root, source)) }
    if (!manifest.targets.includes(target)) { continue }
    const styles = manifest.files.filter(file => file.target === target && file.to.endsWith('.css'))
    if (styles.length !== (source ? 1 : 0)
      || (source && (styles[0].from !== source || styles[0].to !== `src/styles/varo-${name}.css`))) {
      throw new Error(`Style owner mismatch: components/${name} (${target})`)
    }
  }
}
const authoredFiles = await readdir(resolve(root, 'registry/themes/components'), { recursive: true, withFileTypes: true })
for (const file of authoredFiles) {
  if (file.isFile() && file.name.endsWith('.css') && !sourcePaths.has(resolve(file.parentPath, file.name))) {
    throw new Error(`CSS missing from aggregate order: ${resolve(file.parentPath, file.name)}`)
  }
}

const [seed, foundation, agentTokens, agentNativeHelpers] = await Promise.all([
  read('registry/themes/base/seed.json').then(JSON.parse),
  read('registry/themes/base/foundation.css'),
  read('registry/themes/agent/tokens.css'),
  read('registry/themes/agent/native-helpers.css'),
])
const variables = createThemeCssVariables(createTheme(seed))
const projections = new Map()
const sourceCache = new Map()

for (const [target, column, selector, filename] of [
  ['h5', 1, ':root', 'h5.css'],
  ['weapp', 2, 'page', 'weapp-vite.css'],
]) {
  const base = `${renderThemeCssVariables(selector, variables)}\n\n${foundation}`
  projections.set(`registry/themes/base/${filename}`, `${header}${base}`)
  const sections = [base]
  for (const component of components) {
    if (!component[column]) { continue }
    const path = `registry/themes/components/${component[0]}/${component[column]}`
    if (!sourceCache.has(path)) { sourceCache.set(path, await read(path)) }
    sections.push(`/* ${path} */\n${sourceCache.get(path)}`)
  }
  projections.set(`packages/ui-${target}/src/style.css`, `${header}${sections.join('\n')}`)
  const agent = target === 'h5'
    ? agentTokens
    : `${agentTokens.replace(/^:root\s*\{/, 'page {')}\n${agentNativeHelpers}`
  projections.set(`registry/themes/agent/${filename}`, `${header}${agent}`)
}

const changed = await projectFiles(projections, check, { owner: 'styles' })
console.log(`Styles ${check ? 'checked' : 'synchronized'}: ${projections.size} files, ${changed} changed.`)
